In [ ]:
import numpy as np
import pandas as pd
import datetime
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import plotly.figure_factory as ff

In [ ]:
calls = pd.read_excel("Calls_clean.xlsx", dtype={'Id': str, "CONTACTID": str})
contacts = pd.read_excel("Contacts_clean.xlsx", dtype={'Id': str})
spend = pd.read_excel("Spend_clean.xlsx", )
deals = pd.read_excel("Deals_clean.xlsx",dtype={'Id': str, 'Contact Name': str})

display(calls.head())
display(contacts.head())
display(spend.head())
display(deals.head())

id     call_start_time call_owner_name     contactid  \
0  5805028000054113280 2024-06-09 17:29:00  Quincy Vincent  5.805028e+18   
1  5805028000008573952 2023-09-22 11:29:00      Ian Miller  5.805028e+18   
2  5805028000021701632 2023-12-17 17:18:00       Sam Young  5.805028e+18   
3  5805028000049575936 2024-05-12 18:13:00    Julia Nelson  5.805028e+18   
4  5805028000050550784 2024-05-14 16:18:00  Quincy Vincent  5.805028e+18   

  call_type  call_duration_(in_seconds)       call_status  \
0  Outbound                        3600  Attended Dialled   
1  Outbound                        3600  Attended Dialled   
2  Outbound                        3596  Attended Dialled   
3  Outbound                        3593  Attended Dialled   
4  Outbound                        3591  Attended Dialled   

  outgoing_call_status scheduled_in_crm  
0            Completed                0  
1            Completed                0  
2            Completed                0  
3            Completed                0  
4            Completed                0

id contact_owner_name        created_time  \
0  5805028000000645014       Rachel White 2023-06-27 11:28:00   
1  5805028000000872003      Charlie Davis 2023-07-03 11:31:00   
2  5805028000000889001          Bob Brown 2023-07-02 22:37:00   
3  5805028000000907006          Bob Brown 2023-07-03 05:44:00   
4  5805028000000939010         Nina Scott 2023-07-04 10:11:00   

        modified_time  
0 2023-12-22 13:34:00  
1 2024-05-21 10:23:00  
2 2023-12-21 13:17:00  
3 2023-12-29 15:20:00  
4 2024-04-16 16:14:00

date        source               campaign  impressions  spend  clicks  \
0 2023-07-03    Google Ads         gen_analyst_DE            6   0.00       0   
1 2023-07-03    Google Ads  performancemax_eng_DE            4   0.01       1   
2 2023-07-03  Facebook Ads          03.07.23women          187   3.30       6   
3 2023-07-03  Facebook Ads          03.07.23women            4   0.02       1   
4 2023-07-03  Facebook Ads        02.07.23wide_DE           61   0.58       0   

   adgroup       ad  
0  Unknown  Unknown  
1  Unknown  Unknown  
2    women       b3  
3    women       b1  
4     wide       b4

id deal_owner_name closing_date     quality  \
0  5805028000056859489   Ulysses Adams          NaT     Unknown   
1  5805028000056859153        Ben Hall          NaT  B - Medium   
2  5805028000056683030   Charlie Davis          NaT     C - Low   
3  5805028000056558351   Ulysses Adams          NaT     C - Low   
4  5805028000056575242        Ben Hall          NaT     Unknown   

                 stage lost_reason       page               campaign  \
0             New Lead     Unknown    /at-eng                Unknown   
1         Qualificated     Unknown    /at-eng             engwien_AT   
2  Waiting For Payment     Unknown  /eng/test  performancemax_eng_DE   
3  Waiting For Payment     Unknown       /eng                Unknown   
4  Need a consultation     Unknown       /eng        02.07.23wide_DE   

              content        term  ... initial_amount_paid offer_total_amount  \
0             Unknown     Unknown  ...                 0.0             2000.0   
1               b1-at  21_06_2024  ...                 NaN                NaN   
2     _{region_name}_     Unknown  ...              1000.0             9000.0   
3             Unknown     Unknown  ...              1000.0             9000.0   
4  bloggersvideo23com        wide  ...                 NaN                NaN   

          contact_name        city level_of_deutsch_standardized  sla_seconds  \
0  5805028000056834471     Unknown                       Unknown          NaN   
1  5805028000056889019     Unknown                       Unknown       3745.0   
2  5805028000056690015  Crailsheim                       Unknown       1239.0   
3  5805028000056578244    Dortmund                            B1        589.0   
4  5805028000008812393     Unknown                       Unknown       5450.0   

   longitude   latitude  country           federal_state  
0        NaN        NaN  Unknown                 Unknown  
1        NaN        NaN  Unknown                 Unknown  
2  10.063357  49.133735  Germany       Baden-Württemberg  
3   7.465298  51.513587  Germany  North Rhine-Westphalia  
4        NaN        NaN  Unknown                 Unknown  

[5 rows x 27 columns]

# **Анализ временных рядов:**

**1.Анализ тенденции создания сделок с течением времени и их связь с звонками.**

In [ ]:
# Deal Creation Trend (Monthly): Group the deals data by month using the created_time column and count the number of deals.
deals['created_time'] = pd.to_datetime(deals['created_time'], errors='coerce')
deals['created_month'] = deals['created_time'].dt.to_period('M')

monthly_created_deals = (
    deals.groupby('created_month')
    .size()
    .reset_index(name='Created Deals Count (Monthly)')
)

monthly_created_deals['created_month'] = monthly_created_deals['created_month'].astype(str)

print(f'monthly_created_deals:')
display(monthly_created_deals.head())

monthly_created_deals:


created_month  Created Deals Count (Monthly)
0       2023-07                             59
1       2023-08                            122
2       2023-09                            239
3       2023-10                            334
4       2023-11                            423

In [ ]:
# Deal Creation Trend (Weekly): Group the deals data by week using the created_time column and count the number of deals.
deals['created_time'] = pd.to_datetime(deals['created_time'], errors='coerce')
deals['week'] = deals['created_time'].dt.to_period('W')

weekly_created_deals = (
    deals.groupby('week')
    .size()
    .reset_index(name='Created Deals Count (Weekly)')
)

weekly_created_deals['week'] = weekly_created_deals['week'].astype(str)

print(f'weekly_created_deals')
display(weekly_created_deals.head())

weekly_created_deals


week  Created Deals Count (Weekly)
0  2023-07-03/2023-07-09                            11
1  2023-07-10/2023-07-16                            19
2  2023-07-17/2023-07-23                            11
3  2023-07-24/2023-07-30                            16
4  2023-07-31/2023-08-06                            24

In [ ]:
# Call Trend (Weekly): Group the calls data by week using the call_start_time column and count the number of calls.
calls['call_start_time'] = pd.to_datetime(calls['call_start_time'], errors='coerce')
calls['week'] = calls['call_start_time'].dt.to_period('W')

weekly_calls = (
    calls.groupby('week')
    .size()
    .reset_index(name='Calls Count')
)

weekly_calls['week'] = weekly_calls['week'].astype(str)

print(f'calls_weekly_count:')
display(weekly_calls.head())

calls_weekly_count:


week  Calls Count
0  2023-06-26/2023-07-02            7
1  2023-07-03/2023-07-09          142
2  2023-07-10/2023-07-16          348
3  2023-07-17/2023-07-23          694
4  2023-07-24/2023-07-30          617

In [ ]:
# Comparison of Deals and Calls (Weekly): Merge the weekly deals and weekly calls data.
calls_deals_weekly = (
    pd.merge(weekly_created_deals, weekly_calls, on='week', how='outer')
    .fillna(0)
    .sort_values('week')
)

print(f'calls_deals_weekly:')
display(calls_deals_weekly.head())

calls_deals_weekly:


week  Created Deals Count (Weekly)  Calls Count
0  2023-06-26/2023-07-02                           0.0            7
1  2023-07-03/2023-07-09                          11.0          142
2  2023-07-10/2023-07-16                          19.0          348
3  2023-07-17/2023-07-23                          11.0          694
4  2023-07-24/2023-07-30                          16.0          617

In [ ]:
calls['call_start_time'] = pd.to_datetime(calls['call_start_time'], errors='coerce')
calls['month'] = calls['call_start_time'].dt.to_period('M')

monthly_calls = (
    calls.groupby('month')
    .size()
    .reset_index(name='Calls Count')
)

monthly_calls['month'] = monthly_calls['month'].astype(str)

print(f'monthly_calls:')
display(monthly_calls.head())

monthly_calls:


month  Calls Count
0  2023-06            7
1  2023-07         1878
2  2023-08         3857
3  2023-09         4708
4  2023-10         6488

In [ ]:
fig = make_subplots(
    rows=2,
    cols=2,
    subplot_titles=(
        "Звонки по неделям",
        "Созданные сделки по неделям",
        "Динамика звонков по месяцам",
        "Динамика созданных сделок по месяцам",
    ),
    vertical_spacing=0.25
)


# 1.Звонки по неделям
fig.add_trace(
    go.Scatter(
        x=calls_deals_weekly["week"],
        y=calls_deals_weekly["Calls Count"],
        mode="lines+markers",
        name="Звонки (еженедельно)",
        line=dict(color="#1E90FF", width=3, dash="dash"),
        marker=dict(size=7, color="#00BFFF"),
        hovertemplate="Неделя: %{x}<br>Звонки: %{y}<extra></extra>"
    ),
    row=1,
    col=2
)

# 2.Созданные сделки по неделям
fig.add_trace(
    go.Scatter(
        x=calls_deals_weekly["week"],
        y=calls_deals_weekly["Created Deals Count (Weekly)"],
        mode="lines+markers",
        name="Созданные сделки (еженедельно)",
        line=dict(color="#0057B8", width=3),
        marker=dict(size=7, color="#007BFF"),
        hovertemplate="Неделя: %{x}<br>Создано: %{y}<extra></extra>"
    ),
    row=1,
    col=1
)

# 3.Звонки по месяцам
fig.add_trace(
    go.Scatter(
        x=monthly_calls["month"],
        y=monthly_calls["Calls Count"],
        mode="lines+markers",
        name="Звонки (ежемесячно)",
        line=dict(color="#007BFF", width=3),
        marker=dict(size=7, color="#1E90FF"),
        hovertemplate="Месяц: %{x}<br>Звонки: %{y}<extra></extra>"
    ),
    row=2,
    col=1
)

# 4.Созданные сделки по месяцам
fig.add_trace(
    go.Scatter(
        x=monthly_created_deals["created_month"],
        y=monthly_created_deals["Created Deals Count (Monthly)"],
        mode="lines+markers",
        name="Созданные сделки (ежемесячно)",
        line=dict(color="#0057B8", width=3, dash="dot"),
        marker=dict(size=7, color="#4682B4"),
        hovertemplate="Месяц: %{x}<br>Создано: %{y}<extra></extra>"
    ),
    row=2,
    col=2
)


fig.update_layout(
    title_text="Временные ряды: сделки и звонки",
    height=950,
    width=1700,
    showlegend=True,
    template="plotly_white",
    margin=dict(l=60, r=40, t=100, b=80),
    title_font=dict(size=22, color="#003366", family="Arial Black")
)


fig.update_xaxes(title_text="Неделя", row=1, col=2, tickangle=-45, dtick=4)
fig.update_yaxes(title_text="Количество звонков", row=1, col=2)

fig.update_xaxes(title_text="Неделя", row=1, col=1, tickangle=-45, dtick=4)
fig.update_yaxes(title_text="Количество сделок", row=1, col=1)

fig.update_xaxes(title_text="", row=2, col=1, tickangle=-45)
fig.update_yaxes(title_text="Количество звонков", row=2, col=1)

fig.update_xaxes(title_text="", row=2, col=2, tickangle=-45)
fig.update_yaxes(title_text="Количество сделок", row=2, col=2)

fig.update_layout(
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=-0.1,
        xanchor="center",
        x=0.5
    )
)

fig.show()

Динамика создания сделок и количество звонков демонстрируют схожие тенденции с течением времени, особенно при рассмотрении еженедельных данных. Оба показателя в целом растут, с некоторыми колебаниями. Это указывает на потенциальную взаимосвязь между активностью звонков и процессом создания новых сделок. Ежемесячные данные также подтверждают общий тренд роста как для звонков, так и для созданных сделок за анализируемый период.

In [ ]:
# Perform correlation analysis between weekly created deals and weekly calls
correlation = calls_deals_weekly[
    'Created Deals Count (Weekly)'
].corr(calls_deals_weekly['Calls Count'])

print(
    f"Коэффициент корреляции Пирсона между еженедельными "
    f"созданными сделками и звонками: {correlation:.2f}"
)

Коэффициент корреляции Пирсона между еженедельными созданными сделками и звонками: 0.61


In [ ]:
fig = px.scatter(
    calls_deals_weekly,
    x='Calls Count',
    y='Created Deals Count (Weekly)',
    title='Еженедельные звонки против созданных сделок',
    labels={
        'Calls Count': 'Количество звонков (еженедельно)',
        'Created Deals Count (Weekly)': 'Количество созданных сделок (еженедельно)'
    },
    color_continuous_scale=px.colors.sequential.Blues_r,
    hover_data=['week']
)

fig.update_layout(
    width=800,
    height=600,
    template='plotly_white'
)

fig.show()

Диаграмма рассеяния показывает, что точки данных в основном группируются вдоль восходящей линии. Это означает, что с увеличением количества еженедельных звонков, как правило, увеличивается и количество созданных сделок.

Коэффициент корреляции Пирсона, который равен 0.61, подтверждает это наблюдение, указывая на **положительную линейную взаимосвязь** между еженедельными звонками и созданными сделками. Это говорит о том, что активность звонков является важным фактором, связанным с формированием новых сделок в данном наборе данных.

**2.Изучите распределение времени закрытия сделок и продолжительность периода от создания до закрытия.**

In [ ]:
deals['closing_date'] = pd.to_datetime(deals['closing_date'], errors='coerce')
deals['closing_month'] = deals['closing_date'].dt.to_period('M')

monthly_closed_deals = (
    deals.groupby('closing_month')
    .size()
    .reset_index(name='Closed Deals Count (Monthly)')
)

monthly_closed_deals['closing_month'] = monthly_closed_deals['closing_month'].astype(str)

display(monthly_closed_deals.head())

closing_month  Closed Deals Count (Monthly)
0       2023-07                             8
1       2023-08                            40
2       2023-09                            87
3       2023-10                           191
4       2023-11                           263

In [ ]:
# Deal Duration: Calculate the duration of each deal in days by subtracting created_time from closing_date.
deals['created_time'] = pd.to_datetime(deals['created_time'], errors='coerce')
deals['closing_date'] = pd.to_datetime(deals['closing_date'], errors='coerce')
deals['duration_days'] = (deals['closing_date'] - deals['created_time']).dt.days

display(deals[['created_time', 'closing_date', 'duration_days']].head())

created_time closing_date  duration_days
0 2024-06-21 15:23:00          NaT            NaN
1 2024-06-21 10:36:00          NaT            NaN
2 2024-06-20 12:34:00          NaT            NaN
3 2024-06-20 11:16:00          NaT            NaN
4 2024-06-20 09:26:00          NaT            NaN

In [ ]:
deals['closing_date'] = pd.to_datetime(deals['closing_date'], errors='coerce')

deals['closing_week'] = deals['closing_date'].dt.to_period('W')
weekly_closed_deals = (
    deals.groupby('closing_week')
    .size()
    .reset_index(name='Closed Deals Count (Weekly)')
)
weekly_closed_deals['closing_week'] = weekly_closed_deals['closing_week'].astype(str)

# Месяцы
deals['closing_month'] = deals['closing_date'].dt.to_period('M')
monthly_closed_deals = (
    deals.groupby('closing_month')
    .size()
    .reset_index(name='Closed Deals Count (Monthly)')
)
monthly_closed_deals['closing_month'] = monthly_closed_deals['closing_month'].astype(str)

# --- Палитра Blue ---
colors = {
    "line_weekly": "#0057B8",     # насыщенный синий
    "line_monthly": "#1E90FF",    # ярко-голубой
    "histogram": "#4C78A8"        # нейтральный синий
}

fig = make_subplots(
    rows=2,
    cols=1,
    subplot_titles=(
        "Количество закрытых сделок по неделям",
        "Количество закрытых сделок по месяцам",
    ),
    vertical_spacing=0.28
)

fig.add_trace(
    go.Scatter(
        x=weekly_closed_deals['closing_week'],
        y=weekly_closed_deals['Closed Deals Count (Weekly)'],
        mode='lines+markers',
        name='Weekly closed deals',
        line=dict(color=colors["line_weekly"], width=3),
        marker=dict(size=7, color=colors["line_weekly"]),
        hovertemplate="Неделя: %{x}<br>Закрыто: %{y}<extra></extra>"
    ),
    row=1, col=1
)

fig.add_trace(
    go.Scatter(
        x=monthly_closed_deals['closing_month'],
        y=monthly_closed_deals['Closed Deals Count (Monthly)'],
        mode='lines+markers',
        name='Monthly closed deals',
        line=dict(color=colors["line_monthly"], width=3, dash="dot"),
        marker=dict(size=7, color=colors["line_monthly"]),
        hovertemplate="Месяц: %{x}<br>Закрыто: %{y}<extra></extra>"
    ),
    row=2, col=1
)


fig.update_xaxes(
    tickangle=45,
    row=1, col=1,
    showgrid=True,
    gridcolor='rgba(0,0,0,0.1)',
    dtick=4,
    tickfont=dict(size=11)
)
fig.update_yaxes(row=1, col=1, showgrid=True, gridcolor='rgba(0,0,0,0.1)')

fig.update_xaxes(tickangle=45, row=2, col=1, showgrid=True, gridcolor='rgba(0,0,0,0.1)')
fig.update_yaxes(row=2, col=1, showgrid=True, gridcolor='rgba(0,0,0,0.1)')


fig.update_layout(
    width=1400,
    height=950,
    showlegend=True,
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=-0.1,
        xanchor="center",
        x=0.5,
        font=dict(size=12)
    ),
    margin=dict(l=60, r=40, t=100, b=80),
    template='plotly_white',
    title=dict(
        text="Закрытые сделки: недельная, месячная динамика",
        font=dict(size=22, color="#003366", family="Arial Black")
    )
)

fig.show()

Распределение времени закрытия сделок по неделям и месяцам показывает, что количество закрытых сделок колеблется с течением времени, с некоторыми пиками и спадами.


In [ ]:
# Analyze deal duration by stage
deal_duration_by_stage = (
    deals.groupby('stage')['duration_days']
    .agg(['mean', 'median', 'min', 'max'])
    .reset_index()
)

# Rename columns for clarity
deal_duration_by_stage.rename(
    columns={
        'mean': 'Mean Duration (Days)',
        'median': 'Median Duration (Days)',
        'min': 'Minimum Duration (Days)',
        'max': 'Maximum Duration (Days)'
    },
    inplace=True
)

display(deal_duration_by_stage)

stage  Mean Duration (Days)  Median Duration (Days)  \
0               Call Delayed             34.451613                    13.5   
1             Free Education                   NaN                     NaN   
2                       Lost             45.918152                    28.0   
3        Need a consultation                   NaN                     NaN   
4                   New Lead                   NaN                     NaN   
5               Payment Done             37.123810                    17.0   
6               Qualificated                   NaN                     NaN   
7  Registered on Offline Day                   NaN                     NaN   
8      Registered on Webinar                   NaN                     NaN   
9        Waiting For Payment             11.428571                     1.0   

   Minimum Duration (Days)  Maximum Duration (Days)  
0                      0.0                    221.0  
1                      NaN                      NaN  
2                      0.0                    300.0  
3                      NaN                      NaN  
4                      NaN                      NaN  
5                      0.0                    330.0  
6                      NaN                      NaN  
7                      NaN                      NaN  
8                      NaN                      NaN  
9                      0.0                    105.0

In [ ]:
fig = make_subplots(
    rows=1,
    cols=2,
    subplot_titles=(
        "Средняя длительность сделки по стадиям",
        "Распределение длительности сделок (в днях)",
    ),
    horizontal_spacing=0.15,
)

palette = px.colors.sequential.Blues

# Левый график (средняя длительность по стадиям)
fig.add_trace(
    go.Bar(
        x=deal_duration_by_stage.dropna(subset=['Mean Duration (Days)'])['stage'],
        y=deal_duration_by_stage.dropna(subset=['Mean Duration (Days)'])['Mean Duration (Days)'],
        marker=dict(
            color=deal_duration_by_stage.dropna(subset=['Mean Duration (Days)'])['Mean Duration (Days)'],
            colorscale=palette
        ),
        name='Mean Duration',
        hovertemplate="Стадия: %{x}<br>Средняя длительность: %{y:.2f} дней<extra></extra>"
    ),
    row=1, col=1
)

# Правый нижний (гистограмма длительности)
duration = deals['duration_days'].dropna()
fig.add_trace(
    go.Histogram(
        x=duration,
        nbinsx=30,
        name='Duration (days)',
        marker_color=colors["histogram"],
        opacity=0.8,
        hovertemplate="Длительность: %{x}<br>Частота: %{y}<extra></extra>"
    ),
    row=1, col=2
)

# Оформление и стиль
fig.update_layout(
    xaxis_title="Стадия сделки",
    yaxis_title="Средняя длительность (дни)",
    xaxis={'categoryorder': 'total descending'},
    height=600,
    width=1400,
    plot_bgcolor='white',
    paper_bgcolor='white',
    font=dict(size=12),
    title=dict(
        text="Анализ длительности сделок",
        x=0.5,
        y=0.95,
        xanchor='center',
        yanchor='top',
        font=dict(size=20, color='#2F3E46')
    )
)

fig.update_xaxes(title_text="Стадия сделки", row=1, col=1)
fig.update_yaxes(title_text="Средняя длительность (дни)", row=1, col=1)
fig.update_xaxes(title_text="Длительность сделки (дни)", row=1, col=2)
fig.update_yaxes(title_text="Частота", row=1, col=2)


fig.show()

**1. Взаимосвязь создания сделок и звонков:** Мы увидели сильную положительную корреляцию между еженедельным количеством звонков и созданных сделок. Это говорит о том, что активность звонков тесно связана с процессом появления новых сделок. Динамика обоих показателей с течением времени демонстрирует общий восходящий тренд.

**2. Распределение и длительность закрытия сделок:** Анализ показал, что количество закрытых сделок колеблется по неделям и месяцам. При этом, большинство сделок закрываются относительно быстро после их создания, как видно на гистограмме длительности сделок.

Анализ средней длительности по стадиям (на графике представлены 'Payment Done', 'Call Delayed', 'Lost', 'Waiting For Payment') показывает, что:
* Стадии **'Payment Done'** и **'Call Delayed'** имеют наибольшую среднюю длительность, что может указывать на возможные задержки или более долгие процессы на этих этапах.
* Стадия **'Lost'** также демонстрирует значительную среднюю длительность, что говорит о том, что сделки могут долго находиться в работе, прежде чем будут потеряны.
* Стадия **'Waiting For Payment'** имеет относительно короткую среднюю длительность по сравнению с другими представленными на графике стадиями, что может указывать на более быстрый процесс на этом этапе, если он достигнут.

***В целом, проведенный анализ временных рядов помог выявить основные тенденции в создании и закрытии сделок, подтвердить важность активности звонков для формирования новых сделок и определить стадии, требующие, возможно, дополнительного внимания из-за более длительного цикла закрытия.***

# **Анализ эффективности кампаний:**

In [ ]:
# Aggregate spend data by campaign
spend_agg = (
    spend.groupby('campaign')
    .agg(
        total_spend=('spend', 'sum'),
        total_clicks=('clicks', 'sum'),
        total_impressions=('impressions', 'sum')
    )
    .reset_index()
)

# Aggregate deals data by campaign
campaign_perf = (
    deals.groupby('campaign')
    .agg(
        total_deals=('id', 'count'),
        won_deals=('stage', lambda x: (x == 'Payment Done').sum())
    )
    .reset_index()
)

# Calculate conversion rate
campaign_perf['conversion_rate'] = (
    campaign_perf['won_deals'] / campaign_perf['total_deals']
)

# Merge campaign performance with spend data
campaign_perf_with_spend = (
    pd.merge(campaign_perf, spend_agg, on='campaign', how='left')
    .fillna(0)
)

# Calculate Cost Per Won Deal (CPW) and Click-Through Rate (CTR)
campaign_perf_with_spend['CPW'] = (
    campaign_perf_with_spend['total_spend'] / campaign_perf_with_spend['won_deals']
)
campaign_perf_with_spend['CTR'] = (
    campaign_perf_with_spend['total_clicks'] / campaign_perf_with_spend['total_impressions'] * 100
)

# Replace infinite values with NaN
campaign_perf_with_spend[['CPW', 'CTR']] = campaign_perf_with_spend[['CPW', 'CTR']].replace([np.inf, -np.inf], np.nan)

In [ ]:
#Top 10 campaigns with the lowest CPW
display(campaign_perf_with_spend.sort_values('CPW').head(10))

campaign  total_deals  won_deals  conversion_rate  total_spend  \
10        1005start            5          2         0.400000          0.0   
11        1006start            4          3         0.750000          0.0   
20        1704start            5          1         0.200000          0.0   
43  BloggerShina_DE           52         11         0.211538          0.0   
45     Bloggerel_DE            3          2         0.666667          0.0   
50  Jobs_germany_DE            2          1         0.500000          0.0   
46   Bloggernina_DE            7          2         0.285714          0.0   
48           Dis_DE          138         29         0.210145          0.0   
37        ASA_de_DE           27          5         0.185185          0.0   
38         Akademia            1          1         1.000000          0.0   

    total_clicks  total_impressions  CPW  CTR  
10           0.0                0.0  0.0  NaN  
11           0.0                0.0  0.0  NaN  
20           0.0                0.0  0.0  NaN  
43           0.0                0.0  0.0  NaN  
45           0.0                0.0  0.0  NaN  
50           0.0                0.0  0.0  NaN  
46           0.0                0.0  0.0  NaN  
48           0.0                0.0  0.0  NaN  
37           0.0                0.0  0.0  NaN  
38           0.0                0.0  0.0  NaN

In [ ]:
#Top 10 campaigns by conversion rate
display(
    campaign_perf_with_spend
    .sort_values('conversion_rate', ascending=False)
    .head(10)
)

campaign  total_deals  won_deals  conversion_rate  total_spend  \
38         Akademia            1          1             1.00         0.00   
28  20.05.24wide_DE            1          1             1.00        76.72   
34       26.10start            1          1             1.00         0.00   
70           domain            1          1             1.00         0.00   
99       web2311_DE            3          3             1.00         0.00   
91         referral            1          1             1.00         0.00   
76            hanna            1          1             1.00         0.00   
95          uk12_AT            1          1             1.00         0.00   
96            uk_DE            2          2             1.00         0.00   
11        1006start            4          3             0.75         0.00   

    total_clicks  total_impressions    CPW       CTR  
38           0.0                0.0   0.00       NaN  
28          94.0             5870.0  76.72  1.601363  
34           0.0                0.0   0.00       NaN  
70           0.0                0.0   0.00       NaN  
99           0.0                0.0   0.00       NaN  
91           0.0                0.0   0.00       NaN  
76           0.0                0.0   0.00       NaN  
95           0.0                0.0   0.00       NaN  
96           0.0                0.0   0.00       NaN  
11           0.0                0.0   0.00       NaN

In [ ]:
# Sort and slice top-15 campaigns
campaign_perf_top_deals = (
    campaign_perf_with_spend
    .sort_values('total_deals', ascending=False)
    .head(15)[::-1]
)
campaign_perf_top_conversion = (
    campaign_perf_with_spend
    .sort_values('conversion_rate', ascending=False)
    .head(15)[::-1]
)

# Create subplot layout
fig = make_subplots(
    rows=1,
    cols=2,
    subplot_titles=(
        "ТОП-15 кампаний<br>по общему количеству сделок",
        "ТОП-15 кампаний<br>по коэффициенту конверсии"
    )
)

# Add horizontal bar for total deals
fig.add_trace(
    go.Bar(
        x=campaign_perf_top_deals['total_deals'],
        y=campaign_perf_top_deals['campaign'],
        orientation='h',
        name='Total Deals',
        marker=dict(
            color=campaign_perf_top_deals['total_deals'],
            colorscale=px.colors.sequential.Blues,
            showscale=True
        ),
        hovertemplate=(
            "Кампания: %{y}<br>Количество сделок: %{x}<extra></extra>"
        ),
    ),
    row=1,
    col=1
)

# Add horizontal bar for conversion rate
fig.add_trace(
    go.Bar(
        x=campaign_perf_top_conversion['conversion_rate'],
        y=campaign_perf_top_conversion['campaign'],
        orientation='h',
        name='Conversion Rate',
        marker=dict(
            color=campaign_perf_top_conversion['conversion_rate'],
            colorscale=px.colors.sequential.Blues,
            showscale=True
        ),
        hovertemplate=(
            "Кампания: %{y}<br>Конверсия: %{x:.2%}<extra></extra>"
        ),
    ),
    row=1,
    col=2
)

# Layout adjustments
fig.update_layout(
    title_text=(
        "Эффективность кампаний: "
        "Общее количество сделок и Коэффициент конверсии"
    ),
    height=600,
    width=1200,
    showlegend=False,
    plot_bgcolor='white',
    paper_bgcolor='white'
)

fig.update_yaxes(
    automargin=True,
    tickfont=dict(size=10)
)

fig.update_xaxes(title_text='Общее количество сделок', row=1, col=1)
fig.update_xaxes(title_text='Коэффициент конверсии', row=1, col=2)

fig.update_yaxes(title_text='Кампания', row=1, col=1)
fig.update_yaxes(title_text='Кампания', row=1, col=2)

fig.show()


**Кампании с наибольшим количеством сделок** (например, Unknown, performancemax_digitalmarkt_ru_DE) отлично подходят для привлечения большого объема потенциальных клиентов.

**Кампании с высоким коэффициентом конверсии** (например, hanna, domain, web2311_DE) привлекают более качественных лидов, которые с большей вероятностью совершают оплату.

**Важно анализировать обе метрики** (количество сделок и конверсию) вместе с CPW (стоимостью выигранной сделки) и CTR (кликами) для полной картины эффективности и прибыльности каждой кампании. Некоторые кампании могут приносить много лидов, но быть менее прибыльными из-за низкой конверсии или высокого CPW.

In [ ]:
palette = px.colors.sequential.Blues

campaign_perf_top_conversion = campaign_perf_with_spend.sort_values(
    'conversion_rate', ascending=False
).head(15)[::-1]

campaign_perf_top_cpw = campaign_perf_with_spend[
    (campaign_perf_with_spend['CPW'] > 0) & (campaign_perf_with_spend['CPW'].notna())
].sort_values('CPW', ascending=True).head(15)[::-1]

campaign_perf_sorted_ctr = campaign_perf_with_spend.replace([np.inf, -np.inf], np.nan) \
    .dropna(subset=['CTR']).sort_values('CTR', ascending=False).head(15)[::-1]

fig = make_subplots(
    rows=2, cols=2,
    specs=[[{"rowspan": 2}, {}], [None, {}]],
    subplot_titles=(
        "ТОП-15 кампаний<br>по коэффициенту конверсии",
        "ТОП-15 кампаний<br>по наименьшей стоимости за выигранную сделку (CPW)",
        "ТОП-15 кампаний<br>по коэффициенту кликабельности (CTR)"
    )
)

fig.add_trace(
    go.Bar(
        x=campaign_perf_top_conversion['conversion_rate'],
        y=campaign_perf_top_conversion['campaign'],
        orientation='h',
        marker=dict(
            color=campaign_perf_top_conversion['conversion_rate'],
            colorscale=palette,
            showscale=True
        ),
        hovertemplate="Кампания: %{y}<br>Конверсия: %{x:.2%}<extra></extra>",
    ),
    row=1, col=1
)

fig.add_trace(
    go.Bar(
        x=campaign_perf_top_cpw['CPW'],
        y=campaign_perf_top_cpw['campaign'],
        orientation='h',
        marker=dict(
            color=campaign_perf_top_cpw['CPW'],
            colorscale=palette,
            showscale=True
        ),
        hovertemplate="Кампания: %{y}<br>CPW: %{x:.2f}<extra></extra>",
    ),
    row=1, col=2
)

fig.add_trace(
    go.Bar(
        x=campaign_perf_sorted_ctr['CTR'],
        y=campaign_perf_sorted_ctr['campaign'],
        orientation='h',
        marker=dict(
            color=campaign_perf_sorted_ctr['CTR'],
            colorscale=palette,
            showscale=True
        ),
        hovertemplate="Кампания: %{y}<br>CTR: %{x:.2f}%<extra></extra>",
    ),
    row=2, col=2
)

fig.update_layout(
    title={
        'text': "Эффективность кампаний: Конверсия, CPW и CTR",
        'x': 0.5,
        'y': 0.98,
        'xanchor': 'center',
        'yanchor': 'top'
    },
    title_font=dict(size=22, family='Arial', color='#2F3E46'),
    height=1000,
    width=1200,
    showlegend=False,
    plot_bgcolor='white',
    paper_bgcolor='white',
    margin=dict(t=100, b=60, l=80, r=40)
)

fig.update_yaxes(automargin=True, tickfont=dict(size=10))
fig.update_xaxes(title_text='Коэффициент конверсии', row=1, col=1)
fig.update_xaxes(title_text='CPW', row=1, col=2)
fig.update_xaxes(title_text='CTR (%)', row=2, col=2)

fig.update_yaxes(title_text='Кампания', row=1, col=1)
fig.update_yaxes(title_text='Кампания', row=1, col=2)
fig.update_yaxes(title_text='Кампания', row=2, col=2)

fig.show()

**ТОП-15 кампаний по коэффициенту конверсии:** Этот график показывает, какие кампании наиболее эффективно превращают сделки в успешные (оплаченные). Кампании с высоким процентом конверсии привлекают качественных лидов, которые хорошо соответствуют вашему продукту или услуге.

**ТОП-15 кампаний по наименьшей стоимости за выигранную сделку (CPW):** Этот график выделяет кампании, которые являются наиболее рентабельными с точки зрения получения оплаченных сделок. Низкий CPW означает, что вы тратите меньше денег на привлечение одного платящего клиента через эту кампанию. Важно отметить кампании с CPW=0 или NaN, так как это может указывать на органический трафик или отсутствие данных по расходам.

**ТОП-15 кампаний по коэффициенту кликабельности (CTR):** Этот график показывает, насколько привлекательны объявления или ссылки кампании для пользователей. Высокий CTR говорит о том, что ваше сообщение резонирует с аудиторией и побуждает их перейти по ссылке. Однако высокий CTR не всегда означает высокую конверсию или низкий CPW; это зависит от качества трафика и соответствия предложения ожиданиям.

In [ ]:
# Display top 10 campaigns with lowest CPW
display(
    campaign_perf_with_spend
    .sort_values('CPW')
    .head(10)
)

campaign  total_deals  won_deals  conversion_rate  total_spend  \
10        1005start            5          2         0.400000          0.0   
11        1006start            4          3         0.750000          0.0   
20        1704start            5          1         0.200000          0.0   
43  BloggerShina_DE           52         11         0.211538          0.0   
45     Bloggerel_DE            3          2         0.666667          0.0   
50  Jobs_germany_DE            2          1         0.500000          0.0   
46   Bloggernina_DE            7          2         0.285714          0.0   
48           Dis_DE          138         29         0.210145          0.0   
37        ASA_de_DE           27          5         0.185185          0.0   
38         Akademia            1          1         1.000000          0.0   

    total_clicks  total_impressions  CPW  CTR  
10           0.0                0.0  0.0  NaN  
11           0.0                0.0  0.0  NaN  
20           0.0                0.0  0.0  NaN  
43           0.0                0.0  0.0  NaN  
45           0.0                0.0  0.0  NaN  
50           0.0                0.0  0.0  NaN  
46           0.0                0.0  0.0  NaN  
48           0.0                0.0  0.0  NaN  
37           0.0                0.0  0.0  NaN  
38           0.0                0.0  0.0  NaN

CPW=0 или NaN - это может быть связано с отсутствием расходов в данных 'spend' или отсутствием выигранных сделок

In [ ]:
# Display top 10 campaigns with highest conversion rate
display(
    campaign_perf_with_spend
    .sort_values('conversion_rate', ascending=False)
    .head(10)
)

campaign  total_deals  won_deals  conversion_rate  total_spend  \
38         Akademia            1          1             1.00         0.00   
28  20.05.24wide_DE            1          1             1.00        76.72   
34       26.10start            1          1             1.00         0.00   
70           domain            1          1             1.00         0.00   
99       web2311_DE            3          3             1.00         0.00   
91         referral            1          1             1.00         0.00   
76            hanna            1          1             1.00         0.00   
95          uk12_AT            1          1             1.00         0.00   
96            uk_DE            2          2             1.00         0.00   
11        1006start            4          3             0.75         0.00   

    total_clicks  total_impressions    CPW       CTR  
38           0.0                0.0   0.00       NaN  
28          94.0             5870.0  76.72  1.601363  
34           0.0                0.0   0.00       NaN  
70           0.0                0.0   0.00       NaN  
99           0.0                0.0   0.00       NaN  
91           0.0                0.0   0.00       NaN  
76           0.0                0.0   0.00       NaN  
95           0.0                0.0   0.00       NaN  
96           0.0                0.0   0.00       NaN  
11           0.0                0.0   0.00       NaN

In [ ]:
#Top 10 campaigns with the lowest conversion rate
display(
    campaign_perf_with_spend
    .sort_values('conversion_rate', ascending=True)
    .head(10)
)

campaign  total_deals  won_deals  conversion_rate  \
0              01.04.23women_PL            4          0              0.0   
4          05.07.23interests_DE            6          0              0.0   
9           10.07.23wide_com_DE            1          0              0.0   
8          09.02.24berlin_dd_DE            1          0              0.0   
15                    1406start            3          0              0.0   
14      14.11.23wide_webinar_DE            1          0              0.0   
26  20.03.24interests_WebDev_PL            2          0              0.0   
17           15.04.24LAL_ab__PL            1          0              0.0   
29                    2004start            4          0              0.0   
25  20.03.24interests_WebDev_AT            1          0              0.0   

    total_spend  total_clicks  total_impressions  CPW       CTR  
0        357.25         367.0            45956.0  NaN  0.798590  
4        333.73         425.0            26833.0  NaN  1.583871  
9         91.60          98.0             6978.0  NaN  1.404414  
8        179.89         337.0            13993.0  NaN  2.408347  
15         0.00           0.0                0.0  NaN       NaN  
14       310.28         401.0            18128.0  NaN  2.212048  
26       484.76         421.0            50367.0  NaN  0.835865  
17       167.63         129.0            18887.0  NaN  0.683009  
29         0.00           0.0                0.0  NaN       NaN  
25       191.33         117.0            15133.0  NaN  0.773145

In [ ]:
total_campaigns = len(campaign_perf_with_spend)

campaigns_with_zero_conversion = (
    campaign_perf_with_spend[
        campaign_perf_with_spend['conversion_rate'] == 0
    ].shape[0]
)

percentage_zero_conversion = (campaigns_with_zero_conversion / total_campaigns) * 100

print(f"Процент кампаний с коэффициентом конверсии 0%: {percentage_zero_conversion:.2f}%")

Процент кампаний с коэффициентом конверсии 0%: 37.96%


In [ ]:
#Top 10 campaigns by total number of deals (leads)
display(
    campaign_perf_with_spend
    .sort_values('total_deals', ascending=False)
    .head(10)
)

campaign  total_deals  won_deals  \
55                             Unknown          941        261   
85   performancemax_digitalmarkt_ru_DE          386        109   
12                   12.07.2023wide_DE          250         48   
106                  youtube_shorts_DE          244         53   
1                      02.07.23wide_DE          212         52   
13           12.09.23interests_Uxui_DE          142         26   
48                              Dis_DE          138         29   
3             04.07.23recentlymoved_DE          133         30   
2                        03.07.23women          120         30   
6                       07.07.23LAL_DE          114         28   

     conversion_rate  total_spend  total_clicks  total_impressions  \
55          0.277365     15473.68      104787.0          1320035.0   
85          0.282383         0.00           0.0                0.0   
12          0.192000      9471.52       22768.0          3302301.0   
106         0.217213     14149.22       57873.0          8481054.0   
1           0.245283      6913.60       10281.0           594807.0   
13          0.183099      3753.06        6301.0           319463.0   
48          0.210145         0.00           0.0                0.0   
3           0.225564      4523.31        7611.0           417891.0   
2           0.250000      4219.75        7139.0           348089.0   
6           0.245614      4200.37        5813.0           335725.0   

            CPW       CTR  
55    59.286130  7.938199  
85     0.000000       NaN  
12   197.323333  0.689459  
106  266.966415  0.682380  
1    132.953846  1.728460  
13   144.348462  1.972372  
48     0.000000       NaN  
3    150.777000  1.821288  
2    140.658333  2.050912  
6    150.013214  1.731477

Большинство кампаний в этом списке имеют коэффициент конверсии 0.0%. Это означает, что ни одна из сделок, связанных с этими кампаниями, не достигла стадии 'Payment Done' за рассматриваемый период.
Наличие кампаний с нулевой конверсией может указывать на несколько проблем:

**Некачественные лиды**: Кампания привлекает много лидов, но они не соответствуют профилю идеального клиента и не заинтересованы в покупке.
**Проблемы в процессе продаж:** Возможно, лиды из этих кампаний обрабатываются неэффективно отделом продаж.

**Несоответствие маркетингового сообщения и предложения:** То, что обещает кампания, не соответствует тому, что предлагается на следующих этапах взаимодействия.

**Технические проблемы:** Возможно, есть проблемы с отслеживанием конверсий для этих кампаний.

In [ ]:
# Get top 10 campaigns by conversion rate
campaign_perf_top_conversion = campaign_perf_with_spend.nlargest(10, 'conversion_rate')

# Get top 10 campaigns by total deals
campaign_perf_top_deals = campaign_perf_with_spend.nlargest(10, 'total_deals')

# Filter campaigns with won deals > 0 and calculate CPW for those campaigns
campaign_perf_top_cpw = campaign_perf_with_spend[
    campaign_perf_with_spend['won_deals'] > 0
].copy()
campaign_perf_top_cpw['CPW'] = (
    campaign_perf_top_cpw['total_spend'] / campaign_perf_top_cpw['won_deals']
)

# Get top 10 campaigns by CPW
campaign_perf_top_cpw = campaign_perf_top_cpw.nlargest(10, 'CPW')

# Get top 10 campaigns by total spend
campaign_perf_top_spend = campaign_perf_with_spend.nlargest(10, 'total_spend')


fig = make_subplots(
    rows=2, cols=2,
    subplot_titles=(
        'ТОП-10<br>по коэффициенту конверсии',
        'ТОП-10<br>по количеству сделок',
        'ТОП-10<br>по стоимости за выигранную сделку (CPW)',
        'ТОП-10<br>по общим расходам'
    ),
    horizontal_spacing=0.15,
    vertical_spacing=0.18
)

palette = px.colors.sequential.Blues

fig.add_trace(
    go.Bar(
        x=campaign_perf_top_conversion['conversion_rate'],
        y=campaign_perf_top_conversion['campaign'],
        orientation='h',
        marker=dict(
            color=campaign_perf_top_conversion['conversion_rate'],
            colorscale=palette,
            showscale=False
        ),
        name='Коэффициент конверсии'
    ),
    row=1, col=1
)

fig.add_trace(
    go.Bar(
        x=campaign_perf_top_deals['total_deals'],
        y=campaign_perf_top_deals['campaign'],
        orientation='h',
        marker=dict(
            color=campaign_perf_top_deals['total_deals'],
            colorscale=palette,
            showscale=False
        ),
        name='Количество сделок'
    ),
    row=1, col=2
)

fig.add_trace(
    go.Bar(
        x=campaign_perf_top_cpw['CPW'],
        y=campaign_perf_top_cpw['campaign'],
        orientation='h',
        marker=dict(
            color=campaign_perf_top_cpw['CPW'],
            colorscale=palette,
            showscale=False
        ),
        name='CPW'
    ),
    row=2, col=1
)

fig.add_trace(
    go.Bar(
        x=campaign_perf_top_spend['total_spend'],
        y=campaign_perf_top_spend['campaign'],
        orientation='h',
        marker=dict(
            color=campaign_perf_top_spend['total_spend'],
            colorscale=palette,
            showscale=False
        ),
        name='Расходы'
    ),
    row=2, col=2
)

fig.update_layout(
    title={
        'text': "Анализ эффективности кампаний",
        'x': 0.5,
        'y': 0.98,
        'xanchor': 'center',
        'yanchor': 'top'
    },
    title_font=dict(size=22, family='Arial', color='#2F3E46'),
    height=900,
    width=1200,
    showlegend=False,
    plot_bgcolor='white',
    paper_bgcolor='white',
    margin=dict(t=100, b=60, l=70, r=40)
)

for r in [1, 2]:
    for c in [1, 2]:
        fig.update_yaxes(
            automargin=True,
            tickfont=dict(size=10),
            categoryorder='total ascending',
            row=r, col=c
        )

fig.update_xaxes(title_text='Коэффициент конверсии', row=1, col=1)
fig.update_xaxes(title_text='Общее количество сделок', row=1, col=2)
fig.update_xaxes(title_text='Стоимость за выигранную сделку (CPW)', row=2, col=1)
fig.update_xaxes(title_text='Общие расходы', row=2, col=2)

fig.update_yaxes(title_text='Кампания', row=1, col=1)
fig.update_yaxes(title_text='Кампания', row=1, col=2)
fig.update_yaxes(title_text='Кампания', row=2, col=1)
fig.update_yaxes(title_text='Кампания', row=2, col=2)

fig.show()

In [ ]:
# Filter campaigns with valid CPW for comparison
campaign_perf_filtered_cpw = campaign_perf_with_spend[
    (campaign_perf_with_spend['CPW'].notna()) & (campaign_perf_with_spend['CPW'] > 0)
].copy()

fig = px.scatter(
    campaign_perf_filtered_cpw,
    x='conversion_rate',
    y='CPW',
    size='total_deals',  # Use total_deals for bubble size
    color='CPW',        # Color by CPW (lower is better, so use reversed scale)
    hover_name='campaign',
    size_max=60,  # Adjust bubble size for better visualization
    color_continuous_scale=px.colors.sequential.Blues_r, # Use reversed Blues for lower CPW being darker
    title='Campaign Performance: Conversion Rate vs CPW (Bubble size = Total Deals)'
)

fig.update_layout(
    xaxis_title='Conversion Rate',
    yaxis_title='Cost per Won Deal (CPW)',
    height=600,
    width=900,
    template='plotly_white'
)

fig.show()

*   Кампании, которые попадают в ТОП по конверсии и имеют низкий CPW, являются наиболее прибыльными и эффективными. Именно на такие кампании стоит обратить особое внимание для масштабирования.
*   Кампании с высоким объемом сделок (Total Deals), но низкой конверсией или высоким CPW, могут требовать оптимизации. Возможно, они привлекают много лидов, но их качество низкое, или процесс продаж неэффективен для данного типа лидов.
*   Высокие общие расходы на кампанию не всегда коррелируют с ее эффективностью. Важно смотреть на CPW и конверсию, чтобы понять, оправданы ли затраты результатами.




**2. Оцените эффективность различных маркетинговых источников (Source) в генерировании качественных лидов.**

In [ ]:
# Группировка spend по источникам и суммирование метрик
source_spend_analysis = spend.groupby('source').agg(
    Total_Spend=('spend', 'sum'),
    Total_Clicks=('clicks', 'sum'),
    Total_Impressions=('impressions', 'sum')
).reset_index()

display(source_spend_analysis.head(15))

source  Total_Spend  Total_Clicks  Total_Impressions
0         Bloggers      6204.00         10219             599333
1              CRM         0.00          7995                  0
2     Facebook Ads     33754.72         48133            2850200
3       Google Ads     56458.90        239154           31247731
4          Offline         0.00            57                  0
5          Organic         0.00         59128                  0
6      Partnership         0.00           350                  0
7            Radio       300.00             0                  0
8              SMM      2484.52         10423              23772
9   Telegram posts      6466.36         16597             695400
10      Tiktok Ads     11985.67         28268            5007212
11         Webinar      2101.04          2992             285570
12     Youtube Ads     14633.33         59061            8655978

In [ ]:
# Aggregate deals data by source
source_deals_analysis = (
    deals.groupby('source')
    .agg(
        total_deals=('id', 'count'),
        won_deals=('stage', lambda x: (x == 'Payment Done').sum())
    )
    .reset_index()
)

# Aggregate spend data by source
source_spend_analysis = (
    spend.groupby('source')
    .agg(
        total_spend=('spend', 'sum'),
        total_clicks=('clicks', 'sum'),
        total_impressions=('impressions', 'sum')
    )
    .reset_index()
)

# Merge deals and spend data on source
source_full_analysis = pd.merge(
    source_deals_analysis,
    source_spend_analysis,
    on='source',
    how='left'
).fillna(0)

# Calculate conversion rate
source_full_analysis['conversion_rate'] = (
    source_full_analysis['won_deals'] / source_full_analysis['total_deals']
)

# Calculate Cost Per Lead (CPL) and Cost Per Won Deal (CPW)
source_full_analysis['cpl'] = (
    source_full_analysis['total_spend'] / source_full_analysis['total_deals']
)
source_full_analysis['cpw'] = (
    source_full_analysis['total_spend'] / source_full_analysis['won_deals']
)

# Replace infinite values with NaN and handle zero CPL and CPW
source_full_analysis[['cpl', 'cpw']] = source_full_analysis[
    ['cpl', 'cpw']
].replace([np.inf, -np.inf], np.nan)

source_full_analysis['cpl'].fillna(0, inplace=True)

source_full_analysis.loc[source_full_analysis['cpw'] == 0, 'cpw'] = np.nan

/tmp/ipython-input-2253573357.py:48: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.





In [ ]:
display(
    source_full_analysis
    .sort_values('conversion_rate', ascending=False)
    .head(10)
)

source  total_deals  won_deals  total_spend  total_clicks  \
6      Partnership           11          4         0.00           350   
10         Webinar           79         26      2101.04          2992   
5          Organic          468        142         0.00         59128   
1              CRM           82         23         0.00          7995   
7              SMM          351         88      2484.52         10423   
3       Google Ads          683        168     56458.90        239154   
8   Telegram posts          181         39      6466.36         16597   
11     Youtube Ads          246         53     14633.33         59061   
0         Bloggers          182         39      6204.00         10219   
2     Facebook Ads          937        197     33754.72         48133   

    total_impressions  conversion_rate        cpl         cpw  
6                   0         0.363636   0.000000         NaN  
10             285570         0.329114  26.595443   80.809231  
5                   0         0.303419   0.000000         NaN  
1                   0         0.280488   0.000000         NaN  
7               23772         0.250712   7.078405   28.233182  
3            31247731         0.245974  82.663104  336.064881  
8              695400         0.215470  35.725746  165.804103  
11            8655978         0.215447  59.485081  276.100566  
0              599333         0.214286  34.087912  159.076923  
2             2850200         0.210245  36.024248  171.343756

In [ ]:
display(
    source_full_analysis
    .sort_values(by='cpw')
    .head(10)
)

source  total_deals  won_deals  total_spend  total_clicks  \
7              SMM          351         88      2484.52         10423   
10         Webinar           79         26      2101.04          2992   
0         Bloggers          182         39      6204.00         10219   
8   Telegram posts          181         39      6466.36         16597   
2     Facebook Ads          937        197     33754.72         48133   
9       Tiktok Ads          284         56     11985.67         28268   
11     Youtube Ads          246         53     14633.33         59061   
3       Google Ads          683        168     56458.90        239154   
1              CRM           82         23         0.00          7995   
4          Offline            1          0         0.00            57   

    total_impressions  conversion_rate        cpl         cpw  
7               23772         0.250712   7.078405   28.233182  
10             285570         0.329114  26.595443   80.809231  
0              599333         0.214286  34.087912  159.076923  
8              695400         0.215470  35.725746  165.804103  
2             2850200         0.210245  36.024248  171.343756  
9             5007212         0.197183  42.203063  214.029821  
11            8655978         0.215447  59.485081  276.100566  
3            31247731         0.245974  82.663104  336.064881  
1                   0         0.280488   0.000000         NaN  
4                   0         0.000000   0.000000         NaN

In [ ]:
# Top 10 by number of transactions
display(
    source_full_analysis
    .sort_values(by='total_deals', ascending=False)
    .head(10)
)

source  total_deals  won_deals  total_spend  total_clicks  \
2     Facebook Ads          937        197     33754.72         48133   
3       Google Ads          683        168     56458.90        239154   
5          Organic          468        142         0.00         59128   
7              SMM          351         88      2484.52         10423   
9       Tiktok Ads          284         56     11985.67         28268   
11     Youtube Ads          246         53     14633.33         59061   
0         Bloggers          182         39      6204.00         10219   
8   Telegram posts          181         39      6466.36         16597   
1              CRM           82         23         0.00          7995   
10         Webinar           79         26      2101.04          2992   

    total_impressions  conversion_rate        cpl         cpw  
2             2850200         0.210245  36.024248  171.343756  
3            31247731         0.245974  82.663104  336.064881  
5                   0         0.303419   0.000000         NaN  
7               23772         0.250712   7.078405   28.233182  
9             5007212         0.197183  42.203063  214.029821  
11            8655978         0.215447  59.485081  276.100566  
0              599333         0.214286  34.087912  159.076923  
8              695400         0.215470  35.725746  165.804103  
1                   0         0.280488   0.000000         NaN  
10             285570         0.329114  26.595443   80.809231

In [ ]:
campaign_data_for_plots = campaign_perf_with_spend[
    (campaign_perf_with_spend['total_impressions'] > 0) |
    (campaign_perf_with_spend['total_clicks'] > 0) |
    (campaign_perf_with_spend['total_spend'] > 0)
].copy()

palette = px.colors.sequential.Blues

fig = make_subplots(
    rows=1, cols=2,
    subplot_titles=(
        "Зависимость кликов от расходов",
        "Зависимость показов от расходов"
    )
)

clicks_fig = px.scatter(
    campaign_data_for_plots,
    x="total_spend",
    y="total_clicks",
    trendline="ols"
)

fig.add_trace(
    go.Scatter(
        x=campaign_data_for_plots["total_spend"],
        y=campaign_data_for_plots["total_clicks"],
        mode="markers",
        marker=dict(
            color=palette[-2],  # светло-синий
            size=8,
            opacity=0.7
        ),
        name="Клики"
    ),
    row=1, col=1
)

fig.add_trace(
    go.Scatter(
        x=clicks_fig.data[1].x,
        y=clicks_fig.data[1].y,
        mode="lines",
        line=dict(color=palette[1], width=3),
        name="Тренд"
    ),
    row=1, col=1
)

impressions_fig = px.scatter(
    campaign_data_for_plots,
    x="total_spend",
    y="total_impressions",
    trendline="ols"
)

fig.add_trace(
    go.Scatter(
        x=campaign_data_for_plots["total_spend"],
        y=campaign_data_for_plots["total_impressions"],
        mode="markers",
        marker=dict(
            color=palette[-2],
            size=8,
            opacity=0.7
        ),
        name="Показы"
    ),
    row=1, col=2
)

fig.add_trace(
    go.Scatter(
        x=impressions_fig.data[1].x,
        y=impressions_fig.data[1].y,
        mode="lines",
        line=dict(color=palette[1], width=3),
        name="Тренд"
    ),
    row=1, col=2
)

fig.update_xaxes(title_text="Общие расходы", showgrid=False)
fig.update_yaxes(showgrid=False)
fig.update_yaxes(title_text="Общее количество кликов", row=1, col=1)
fig.update_yaxes(title_text="Общее количество показов", row=1, col=2)

fig.update_layout(
    title={
        "text": "Анализ зависимости расходов от кликов и показов",
        "x": 0.5,
        "y": 0.97,
        "xanchor": "center",
        "yanchor": "top"
    },
    title_font=dict(size=20, color="#2F3E46"),
    height=500,
    width=1000,
    showlegend=False,
    plot_bgcolor="white",
    paper_bgcolor="white",
    margin=dict(t=100, b=50, l=60, r=40)
)

fig.show()

Эти графики демонстрируют прямую зависимость: с увеличением расходов на маркетинговые кампании, как правило, увеличивается и количество кликов, и количество показов. Это ожидаемый результат, поскольку больший бюджет позволяет охватить более широкую аудиторию и получить больше взаимодействий.

In [ ]:
spend = spend[(spend['spend'] > 0) & (spend['clicks'] > 0)].copy()

palette = px.colors.sequential.Blues

fig = px.scatter(
    spend,
    x='spend',
    y='clicks',
    log_x=True,
    log_y=True,
    opacity=0.7,
    title='Зависимость кликов от расходов (лог-шкалы)',
    labels={'spend': 'Расходы (Spend)', 'clicks': 'Клики (Clicks)'},
    color_discrete_sequence=[palette[-2]]
)

fig.update_traces(
    marker=dict(
        color=palette[-2],
        size=8,
        line=dict(width=0.5, color=palette[1])
    )
)

fig.update_layout(
    width=800,
    height=600,
    plot_bgcolor='white',
    paper_bgcolor='white',
    showlegend=False,
    title=dict(
        text="Зависимость кликов от расходов (лог-шкалы)",
        x=0.5,
        xanchor='center',
        y=0.95
    ),
    title_font=dict(size=20, color='#2F3E46'),
    margin=dict(t=80, b=50, l=60, r=40)
)

fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)

fig.show()

Использование логарифмической шкалы на этом графике помогает лучше увидеть распределение данных и зависимости для кампаний с как низкими, так и высокими расходами и кликами. Даже с логарифмическим масштабом, мы всё ещё видим общую тенденцию: чем больше расходы, тем больше кликов.

In [ ]:
# Heatmap корреляций между метриками кампаний (отдельным графиком)
correlation_metrics = campaign_perf_with_spend[
    ['total_spend', 'total_clicks', 'total_impressions',
     'total_deals', 'won_deals', 'conversion_rate', 'CPW', 'CTR']
].dropna()

corr_matrix = correlation_metrics.corr().round(2)

palette = px.colors.sequential.Blues

fig = ff.create_annotated_heatmap(
    z=corr_matrix.values,
    x=list(corr_matrix.columns),
    y=list(corr_matrix.index),
    annotation_text=corr_matrix.values,
    colorscale=palette,
    showscale=True,
    reversescale=True
)

fig.update_layout(
    title=dict(
        text="Корреляции между метриками кампаний",
        x=0.5,
        xanchor='center',
        y=0.97
    ),
    title_font=dict(size=20, color='#2F3E46'),
    width=800,
    height=700,
    plot_bgcolor='white',
    paper_bgcolor='white',
    margin=dict(t=100, l=100, r=60, b=80)
)

fig.update_xaxes(side='bottom', tickangle=45)
fig.update_yaxes(autorange='reversed')

fig.show()

*   Видно сильную положительную корреляцию между расходами (total_spend), кликами (total_clicks) и показами (total_impressions), что логично: чем больше тратится, тем больше показов и кликов получается.
*   ListenТакже наблюдается сильная положительная корреляция между общим количеством сделок (total_deals) и выигранными сделками (won_deals), что ожидаемо.
*  Корреляция между расходами и выигранными сделками или конверсией может быть менее сильной, что подчеркивает важность не только привлечения трафика, но и его качества и эффективности процесса продаж.eintrag

 *  Высокий CPW (дорогая выигранная сделка) может быть связан с высокими расходами или низкой конверсией.



In [ ]:
palette = px.colors.sequential.Blues

# Sort and filter dataframes for each metric
df1 = source_full_analysis.sort_values('total_deals', ascending=False)
df2 = source_full_analysis.sort_values('conversion_rate', ascending=False)
df3 = (
    source_full_analysis[
        (source_full_analysis['cpl'].notna()) & (source_full_analysis['cpl'] > 0)
    ]
    .sort_values('cpl')
    .head(15)
)
df4 = (
    source_full_analysis[
        (source_full_analysis['cpw'].notna()) & (source_full_analysis['cpw'] > 0)
    ]
    .sort_values('cpw')
    .head(15)
)

# Create subplot layout: 2 by 2 grid
fig = make_subplots(
    rows=2,
    cols=2,
    subplot_titles=(
        'Общее количество сделок по источникам',
        'Коэффициент конверсии по источникам',
        'Стоимость привлечения лида (CPL) по источникам (исключая 0)',
        'Стоимость выигранной сделки (CPW) по источникам (исключая 0)'
    ),
)

# Add horizontal bars for each subplot
fig.add_trace(
    go.Bar(
        x=df1['total_deals'],
        y=df1['source'],
        orientation='h',
        marker=dict(color=df1['total_deals'], colorscale=palette, showscale=True),
    ),
    row=1,
    col=1,
)

fig.add_trace(
    go.Bar(
        x=df2['conversion_rate'],
        y=df2['source'],
        orientation='h',
        marker=dict(color=df2['conversion_rate'], colorscale=palette, showscale=True),
    ),
    row=1,
    col=2,
)

fig.add_trace(
    go.Bar(
        x=df3['cpl'],
        y=df3['source'],
        orientation='h',
        marker=dict(color=df3['cpl'], colorscale=palette, showscale=True),
    ),
    row=2,
    col=1,
)

fig.add_trace(
    go.Bar(
        x=df4['cpw'],
        y=df4['source'],
        orientation='h',
        marker=dict(color=df4['cpw'], colorscale=palette, showscale=True),
    ),
    row=2,
    col=2,
)

# Update axes and layout for readability
for r, c in [(1, 1), (1, 2), (2, 1), (2, 2)]:
    fig.update_yaxes(automargin=True, tickfont=dict(size=10), row=r, col=c)
    fig.update_xaxes(tickangle=30, tickfont=dict(size=10), row=r, col=c)
    fig.update_yaxes(categoryorder='total ascending', row=r, col=c)

# Axis titles
fig.update_xaxes(title_text='Количество сделок', row=1, col=1)
fig.update_yaxes(title_text='Источник', row=1, col=1)
fig.update_xaxes(title_text='Коэффициент конверсии', row=1, col=2)
fig.update_yaxes(title_text='Источник', row=1, col=2)
fig.update_xaxes(title_text='CPL', row=2, col=1)
fig.update_yaxes(title_text='Источник', row=2, col=1)
fig.update_xaxes(title_text='CPW', row=2, col=2)
fig.update_yaxes(title_text='Источник', row=2, col=2)

# Final layout adjustments
fig.update_layout(
    height=900,
    width=1400,
    showlegend=False,
    plot_bgcolor='white',
    paper_bgcolor='white',
    title=dict(
        text="Анализ эффективности источников привлечения",
        x=0.5,
        y=0.98,
        xanchor='center',
        yanchor='top',
        font=dict(size=20, color='#2F3E46'),
    ),
    margin=dict(t=120, b=100, l=80, r=50),
)

fig.show()

**Общее количество сделок по источникам:** Показывает, какие источники приносят наибольший объем лидов. Источники с высоким показателем здесь важны для поддержания воронки продаж полной.

**Коэффициент конверсии по источникам:** Демонстрирует, насколько хорошо лиды из каждого источника превращаются в оплаченные сделки. Высокая конверсия указывает на качественный трафик.

**Стоимость привлечения лида (CPL) по источникам (исключая 0):** Показывает, сколько стоит привлечение одного лида из платных источников. Низкий CPL говорит о рентабельности привлечения на верхних этапах воронки.

**Стоимость выигранной сделки (CPW) по источникам (исключая 0):** Это один из наиболее важных показателей, показывающий, сколько стоит получение одной оплаченной сделки из платного источника. Низкий CPW указывает на высокую эффективность источника с точки зрения конечного результата и прибыльности.

В ходе анализа были рассмотрены эффективность кампаний и источников по нескольким ключевым метрикам: общее количество сделок (лидов), коэффициент конверсии (доля оплаченных сделок), стоимость выигранной сделки (CPW), стоимость привлечения лида (CPL), кликабельность (CTR), расходы, показы и клики.

**Основные выводы:**

**1. Не все кампании одинаково эффективны:** Были выявлены кампании, которые приносят большой объем лидов (например, "Unknown", "performancemax_digitalmarkt_ru_DE", "youtube_shorts_DE"), и кампании с высоким коэффициентом конверсии, привлекающие более "качественных" лидов (например, "hanna", "domain", "web2311_DE").

**2. Высокий процент кампаний с нулевой конверсией:** Значительная доля кампаний не привела ни к одной оплаченной сделке за рассматриваемый период (56.21%). Это указывает на серьезные проблемы, которые могут быть связаны с качеством лидов, процессом продаж, несоответствием маркетингового сообщения или техническими проблемами с отслеживанием.

**3. Важность комплексного анализа:** Анализ только одной метрики, такой как общее количество лидов или расходы, недостаточен. Необходимо смотреть на комбинацию метрик, особенно на коэффициент конверсии и CPW, чтобы оценить реальную прибыльность и эффективность кампаний.

**4.Зависимость кликов/показов от расходов:**  Как и ожидалось, существует прямая зависимость между расходами на кампанию, количеством кликов и показов. Однако, это не гарантирует высокую конверсию или низкий CPW.

**5.Эффективность источников:** Анализ по источникам также показал существенные различия. Некоторые источники могут приносить большой объем лидов (например, Facebook Ads, Google Ads), в то время как другие могут иметь более высокий коэффициент конверсии или низкий CPW (например, Organic, Webinar, SMM).

**6.Корреляции между метриками:** Тепловая карта корреляций подтвердила логичные связи (например, между расходами, кликами и показами) и выявила более слабые связи между расходами и конечными результатами (выигранные сделки, конверсия), что подчеркивает сложность оптимизации на всех этапах воронки.


**Рекомендации для дальнейших действий:**

* Исследовать кампании с нулевой конверсией: Провести детальный анализ причин низкой эффективности этих кампаний. Возможно, потребуется пересмотреть таргетинг, маркетинговое сообщение, процесс обработки лидов отделом продаж или проверить технические настройки отслеживания.
* Масштабировать успешные кампании и источники: Увеличить инвестиции в кампании и источники с высоким коэффициентом конверсии и низким CPW, так как они наиболее прибыльны.
* Оптимизировать менее эффективные кампании: Для кампаний с высоким объемом лидов, но низкой конверсией или высоким CPW, искать возможности оптимизации. Это может включать улучшение качества лидов, доработку процесса продаж, A/B тестирование креативов и посадочных страниц.
* Углубиться в анализ по сегментам: Если возможно, провести анализ эффективности по более детальным сегментам (например, по географии, демографии, интересам), чтобы выявить дополнительные закономерности.

# **Анализ эффективности работы отдела продаж:**

In [ ]:
# Group deals by deal owner and calculate counts
deals_by_owner = (
    deals.groupby('deal_owner_name')
    .agg(
        total_deals_handled=('id', 'count'),
        won_deals_count=('stage', lambda x: (x == 'Payment Done').sum())
    )
    .reset_index()
)

display(deals_by_owner.head())

deal_owner_name  total_deals_handled  won_deals_count
0        Ben Hall                  309               46
1       Bob Brown                    1                0
2    Cara Iverson                  100               26
3   Charlie Davis                  441              148
4     Diana Evans                   80                1

In [ ]:
# Calculate conversion rate per deal owner
deals_by_owner['conversion_rate'] = (
    deals_by_owner['won_deals_count'] / deals_by_owner['total_deals_handled']
)

# Display top owners sorted by conversion rate descending
display(
    deals_by_owner.sort_values('conversion_rate', ascending=False).head()
)

deal_owner_name  total_deals_handled  won_deals_count  conversion_rate
6      George King                    2                2         1.000000
3    Charlie Davis                  441              148         0.335601
14   Oliver Taylor                  151               50         0.331126
11    Kevin Parker                   81               26         0.320988
5         Eva Kent                   62               18         0.290323

In [ ]:
# Aggregate deal counts and won deals per campaign
campaign_perf = (
    deals.groupby('campaign')
    .agg(
        total_deals=('id', 'count'),
        won_deals=('stage', lambda x: (x == 'Payment Done').sum())
    )
    .reset_index()
)

# Calculate conversion rate
campaign_perf['conversion_rate'] = campaign_perf['won_deals'] / campaign_perf['total_deals']

# Display top 10 campaigns by conversion rate descending
display(
    campaign_perf.sort_values('conversion_rate', ascending=False).head(10)
)

campaign  total_deals  won_deals  conversion_rate
38         Akademia            1          1             1.00
28  20.05.24wide_DE            1          1             1.00
34       26.10start            1          1             1.00
70           domain            1          1             1.00
99       web2311_DE            3          3             1.00
91         referral            1          1             1.00
76            hanna            1          1             1.00
95          uk12_AT            1          1             1.00
96            uk_DE            2          2             1.00
11        1006start            4          3             0.75

In [ ]:
# Calculate total sales amount per deal owner
total_sales = (
    deals.groupby('deal_owner_name')['offer_total_amount']
    .sum()
    .reset_index()
)

# Merge the total sales into existing deals_by_owner DataFrame
deals_by_owner = deals_by_owner.merge(total_sales, on='deal_owner_name', how='left')

# Rename the new column for clarity
deals_by_owner.rename(columns={'offer_total_amount': 'total_sales_amount'}, inplace=True)

# Drop duplicate columns if any
deals_by_owner = deals_by_owner.loc[:,~deals_by_owner.columns.duplicated()]

# Display the top deal owners by total sales amount descending
display(deals_by_owner.sort_values('total_sales_amount', ascending=False).head())

deal_owner_name  total_deals_handled  won_deals_count  conversion_rate  \
18    Ulysses Adams                  609              140         0.229885   
3     Charlie Davis                  441              148         0.335601   
10     Julia Nelson                  387               91         0.235142   
15  Paula Underwood                  337               91         0.270030   
19    Victor Barnes                  256               44         0.171875   

    total_sales_amount  
18           4936000.0  
3            3747200.0  
10           3490820.0  
15           2766500.0  
19           2197000.0

In [ ]:
deals_by_owner_sorted_conversion = (
    deals_by_owner
    .sort_values('conversion_rate', ascending=False)
    .head(10)
)

deals_by_owner_sorted_sales = (
    deals_by_owner
    .sort_values('total_sales_amount', ascending=False)
    .head(10)
)

campaign_perf_sorted_conversion = (
    campaign_perf_with_spend
    .sort_values('conversion_rate', ascending=False)
    .head(15)
)

campaign_perf_sorted_sales = (
    campaign_perf_with_spend
    .sort_values('total_spend', ascending=False)
    .head(15)
)


fig = make_subplots(
    rows=2, cols=2,
    subplot_titles=[
        'Коэффициент конверсии по владельцам сделок',
        'Общая сумма продаж по владельцам сделок',
        'ТОП-15 кампаний по коэффициенту конверсии',
        'ТОП-15 кампаний по общей сумме продаж'
    ]
)

fig.add_trace(go.Bar(
    x=deals_by_owner_sorted_conversion['deal_owner_name'],
    y=deals_by_owner_sorted_conversion['conversion_rate'],
    marker=dict(
        color=deals_by_owner_sorted_conversion['conversion_rate'],
        colorscale=px.colors.sequential.Blues,
        showscale=True
    )
), row=1, col=1)

fig.add_trace(go.Bar(
    x=deals_by_owner_sorted_sales['deal_owner_name'],
    y=deals_by_owner_sorted_sales['total_sales_amount'],
    marker=dict(
        color=deals_by_owner_sorted_sales['total_sales_amount'],
        colorscale=px.colors.sequential.Blues,
        showscale=True
    )
), row=1, col=2)

fig.add_trace(go.Bar(
    y=campaign_perf_sorted_conversion['campaign'],
    x=campaign_perf_sorted_conversion['conversion_rate'],
    orientation='h',
    marker=dict(
        color=campaign_perf_sorted_conversion['conversion_rate'],
        colorscale=px.colors.sequential.Blues,
        showscale=True
    )
), row=2, col=1)

fig.add_trace(go.Bar(
    y=campaign_perf_sorted_sales['campaign'],
    x=campaign_perf_sorted_sales['total_spend'],
    orientation='h',
    marker=dict(
        color=campaign_perf_sorted_sales['total_spend'],
        colorscale=px.colors.sequential.Blues,
        showscale=True
    )
), row=2, col=2)

for r, c in [(1,1), (1,2), (2,1), (2,2)]:
    fig.update_xaxes(tickangle=45, tickfont=dict(size=10), row=r, col=c)
    fig.update_yaxes(automargin=True, tickfont=dict(size=10), row=r, col=c)

fig.update_xaxes(title_text='Владелец сделки', row=1, col=1)
fig.update_yaxes(title_text='Коэффициент конверсии', row=1, col=1)
fig.update_xaxes(title_text='Владелец сделки', row=1, col=2)
fig.update_yaxes(title_text='Общая сумма продаж', row=1, col=2)
fig.update_xaxes(title_text='Кампания', row=2, col=1)
fig.update_yaxes(title_text='Коэффициент конверсии', row=2, col=1)
fig.update_xaxes(title_text='Кампания', row=2, col=2)
fig.update_yaxes(title_text='Общая сумма продаж', row=2, col=2)

fig.update_layout(
    height=900,
    width=1400,
    showlegend=False,
    title=dict(
        text='Анализ эффективности работы отдела продаж и кампаний',
        x=0.5,
        xanchor='center',
        yanchor='top',
        font=dict(size=20, color='#2F3E46')
    ),
    plot_bgcolor='white',
    paper_bgcolor='white',
    margin=dict(b=150, t=80)
)

fig.update_yaxes(categoryorder='total ascending', row=2, col=1)
fig.update_yaxes(categoryorder='total ascending', row=2, col=2)

fig.show()

Эти графики показывают эффективность владельцев сделок и маркетинговых кампаний по ключевым метрикам: коэффициенту конверсии и общей сумме продаж.

**По владельцам сделок:** Выделяются менеджеры как с высокой конверсией, так и с наибольшим объемом продаж. Это помогает определить лучших продавцов и тех, кому может потребоваться поддержка.

**По кампаниям:** Определены кампании, которые наиболее успешно конвертируют лиды в оплату, и те, которые приносят наибольший доход. Это важно для оптимизации маркетинговых инвестиций и понимания, какие каналы наиболее прибыльны.

Совмещение этих видов анализа позволяет понять, какие менеджеры лучше работают с лидами из определенных кампаний и где есть потенциал для улучшения как в продажах, так и в маркетинге.

In [ ]:
fig = px.violin(
    deals,
    x='stage',
    y='duration_days',
    color='stage',
    box=True,
    points='outliers',
    color_discrete_sequence=px.colors.sequential.Blues[2:]
)

fig.update_layout(
    title='Распределение длительности сделок по стадиям',
    xaxis_title='Стадия сделки',
    yaxis_title='Длительность сделки',
    xaxis_tickangle=45,
    plot_bgcolor='white',
    paper_bgcolor='white',
    width=1200,
    height=800
)

fig.show()

Вывод: анализ длительности сделок по стадиям

Наибольшая длительность сделок наблюдается на стадиях “Call Delayed”, “Lost” и “Payment Done” — до 300+ дней, что указывает на возможные задержки в процессе.

“Waiting for Payment” — самая быстрая стадия: клиенты либо быстро совершают оплату, либо уходят в отказ.

Стадии “Qualified” и “Need a consultation” имеют умеренную длительность.

Значительный разброс на стадиях “Lost” и “Payment Done” говорит о высокой вариативности пути сделки до завершения.

In [ ]:
# Calculate conversion rate for each combination of deal owner and campaign
owner_campaign_conversion = (
    deals.groupby(['deal_owner_name', 'campaign'])
    .agg(
        total_deals=('id', 'count'),
        won_deals=('stage', lambda x: (x == 'Payment Done').sum())
    )
    .reset_index()
)

owner_campaign_conversion['conversion_rate'] = (
    owner_campaign_conversion['won_deals'] / owner_campaign_conversion['total_deals']
)

# Create a pivot table of conversion rate by deal owner and campaign
owner_campaign_conversion_pivot = (
    owner_campaign_conversion
    .pivot(
        index='deal_owner_name',
        columns='campaign',
        values='conversion_rate'
    )
    .fillna(0)
)

display(owner_campaign_conversion_pivot.head())

campaign         01.04.23women_PL  02.07.23wide_DE  03.07.23women  \
deal_owner_name                                                     
Ben Hall                      0.0         0.208333       0.000000   
Bob Brown                     0.0         0.000000       0.000000   
Cara Iverson                  0.0         0.500000       0.000000   
Charlie Davis                 0.0         0.300000       0.416667   
Diana Evans                   0.0         0.166667       0.000000   

campaign         04.07.23recentlymoved_DE  05.07.23interests_DE  \
deal_owner_name                                                   
Ben Hall                         0.166667                   0.0   
Bob Brown                        0.000000                   0.0   
Cara Iverson                     0.000000                   0.0   
Charlie Davis                    0.304348                   0.0   
Diana Evans                      0.000000                   0.0   

campaign         05.09.2023wide_DE  07.07.23LAL_DE  08.04.24wide_webinar_DE  \
deal_owner_name                                                               
Ben Hall                       0.0        0.071429                 0.000000   
Bob Brown                      0.0        0.000000                 0.000000   
Cara Iverson                   0.0        1.000000                 0.333333   
Charlie Davis                  0.0        0.428571                 0.000000   
Diana Evans                    0.0        0.000000                 0.000000   

campaign         09.02.24berlin_dd_DE  10.07.23wide_com_DE  ...  web2211_DE  \
deal_owner_name                                             ...               
Ben Hall                          0.0                  0.0  ...         0.0   
Bob Brown                         0.0                  0.0  ...         0.0   
Cara Iverson                      0.0                  0.0  ...         0.0   
Charlie Davis                     0.0                  0.0  ...         0.0   
Diana Evans                       0.0                  0.0  ...         0.0   

campaign         web2311_DE  web2408_DE  webinar1604  webinar1906   work_DE  \
deal_owner_name                                                               
Ben Hall                0.0         0.0     0.000000          0.0  0.000000   
Bob Brown               0.0         0.0     0.000000          0.0  0.000000   
Cara Iverson            0.0         0.0     1.000000          0.0  0.333333   
Charlie Davis           0.0         1.0     0.333333          0.0  0.200000   
Diana Evans             0.0         0.0     0.000000          0.0  0.000000   

campaign         workingin_DE  yo_DE  youtube_shorts_DE  youtube_shortsin_AT  
deal_owner_name                                                               
Ben Hall                  0.0    0.0           0.190476                  0.0  
Bob Brown                 0.0    0.0           0.000000                  0.0  
Cara Iverson              0.0    0.0           0.166667                  0.0  
Charlie Davis             0.0    0.0           0.240000                  0.0  
Diana Evans               0.0    0.0           0.000000                  0.0  

[5 rows x 108 columns]

In [ ]:
# Calculate total sales amount for each combination of deal owner and campaign
owner_campaign_sales = deals.groupby(['deal_owner_name', 'campaign']).agg(
    total_sales=('offer_total_amount', 'sum')
).reset_index()

display(owner_campaign_sales.head())

deal_owner_name                  campaign  total_sales
0        Ben Hall          01.04.23women_PL       4000.0
1        Ben Hall           02.07.23wide_DE     111500.0
2        Ben Hall             03.07.23women      53000.0
3        Ben Hall  04.07.23recentlymoved_DE      31500.0
4        Ben Hall            07.07.23LAL_DE     124000.0

In [ ]:
# Calculate conversion rate for each combination of deal owner and campaign
owner_campaign_sales = (
    deals.groupby(['deal_owner_name', 'campaign'])
    .agg(total_sales=('offer_total_amount', 'sum'))
    .reset_index()
)

display(owner_campaign_sales.head())

deal_owner_name                  campaign  total_sales
0        Ben Hall          01.04.23women_PL       4000.0
1        Ben Hall           02.07.23wide_DE     111500.0
2        Ben Hall             03.07.23women      53000.0
3        Ben Hall  04.07.23recentlymoved_DE      31500.0
4        Ben Hall            07.07.23LAL_DE     124000.0

In [ ]:
display(owner_campaign_conversion.describe())

total_deals   won_deals  conversion_rate
count   530.000000  530.000000       530.000000
mean      6.613208    1.575472         0.223547
std      14.365714    4.250093         0.319104
min       1.000000    0.000000         0.000000
25%       1.000000    0.000000         0.000000
50%       2.000000    0.000000         0.000000
75%       5.000000    1.000000         0.333333
max     155.000000   50.000000         1.000000

In [ ]:
# Create a pivot table of conversion rate by deal owner and campaign
owner_campaign_conversion_pivot = (
    owner_campaign_conversion
    .pivot(
        index='deal_owner_name',
        columns='campaign',
        values='conversion_rate'
    )
    .fillna(0)
)

# Create heatmap figure
fig = go.Figure(
    data=go.Heatmap(
        z=owner_campaign_conversion_pivot.values,
        x=owner_campaign_conversion_pivot.columns,
        y=owner_campaign_conversion_pivot.index,
        colorscale=px.colors.sequential.Blues,
        colorbar=dict(title='Коэффициент конверсии'),
        hoverinfo='x+y+z'
    )
)

# Update layout with titles and sizing
fig.update_layout(
    title='Тепловая карта коэффициента конверсии по владельцам сделок и кампаниям',
    xaxis_title='Кампания',
    yaxis_title='Владелец сделки',
    height=800,
    width=1000
)

fig.show()

Тепловая карта наглядно показывает, как различается эффективность конверсии сделок у разных менеджеров в зависимости от маркетинговой кампании. Более темные (синие) области указывают на комбинации "владелец сделки - кампания" с более высоким коэффициентом конверсии, что свидетельствует об успешной работе менеджера с лидами из данной кампании. Светлые области (или 0) показывают низкую конверсию или отсутствие сделок. Этот график помогает выявить как наиболее успешные связки менеджеров и кампаний, так и области, где конверсия низкая и требуется дополнительный анализ или обучение.

In [ ]:
owner_campaign_sales_filtered = owner_campaign_sales[
    owner_campaign_sales['total_sales'] > 0
]

# Создание сводной таблицы для коэффициента конверсии
owner_campaign_conversion_pivot = (
    owner_campaign_conversion
    .pivot(
        index='deal_owner_name',
        columns='campaign',
        values='conversion_rate'
    )
    .fillna(0)
)

fig = px.scatter(
    owner_campaign_sales_filtered,
    x='deal_owner_name',
    y='campaign',
    size='total_sales',
    color='total_sales',
    color_continuous_scale=px.colors.sequential.Blues_r,
    hover_name='campaign',
    size_max=60,
    title='Вклад ТОП-15 кампаний в общую выручку по владельцам сделок (Bubble Chart)',
    labels={
        'total_sales': 'Общая сумма продаж',
        'deal_owner_name': 'Владелец сделки',
        'campaign': 'Кампания'
    }
)

fig.update_layout(
    xaxis_title='Владелец сделки',
    yaxis_title='Кампания',
    height=800,
    width=1200,
    plot_bgcolor='white',
    paper_bgcolor='white'
)

fig.show()

* Высокоэффективные комбинации: На графике видны комбинации "владелец сделки - кампания", где размер пузырька наибольший. Это указывает на менеджеров, которые успешно закрывают сделки, приносящие наибольшую выручку из конкретных кампаний. Такие комбинации могут быть примером лучших практик.

* Распределение выручки: График показывает, как выручка распределяется между менеджерами и какие кампании являются основными источниками дохода. Это помогает понять, насколько сбалансирована нагрузка и эффективность среди менеджеров по разным кампаниям.

* Потенциал для оптимизации: Если определенный менеджер работает с кампанией, приносящей много сделок (видно из предыдущих графиков), но на этом графике соответствующий пузырек маленький или отсутствует, это может указывать на проблему с конверсией лидов из этой кампании у данного менеджера.

В целом, график помогает выявить как сильные стороны (успешные менеджеры и прибыльные кампании), так и области для улучшения (менеджеры или кампании с низким вкладом в выручку).

**Выводы по анализу эффективности работы отдела продаж:**

На основе всего проведенного анализа можно выделить следующие сильные и слабые стороны в работе отдела продаж:

**Сильные стороны:**

*   **Общий рост активности:** Анализ временных рядов показал положительную динамику по количеству звонков, созданных и закрытых сделок, особенно с конца 2023 года и в 2024 году. Это свидетельствует об общем росте активности отдела и потенциала продаж.
*   **Эффективные владельцы сделок:** Выявлены менеджеры с высоким коэффициентом конверсии и/или значительным вкладом в общую сумму продаж. Это указывает на наличие сильных продавцов в команде, которые успешно работают с лидами и закрывают сделки.
*   **Эффективные кампании и источники:** Определены кампании и источники трафика, которые приносят качественные лиды с высокой конверсией. Это говорит о том, что маркетинговые усилия в целом успешны в привлечении потенциальных клиентов.
*   **Короткий цикл продаж для большинства сделок:** Распределение длительности сделок показало, что значительная часть сделок закрывается относительно быстро, что может быть признаком отлаженных процессов продаж для определенных типов лидов или продуктов.
*   **Сильная корреляция между звонками и созданными сделками:** Это подчеркивает важность активной работы менеджеров с потенциальными клиентами по телефону.

**Слабые стороны и области для улучшения:**

*   **Низкая конверсия у некоторых владельцев сделок:** Наличие менеджеров с низким коэффициентом конверсии может указывать на потребность в дополнительном обучении, коучинге или перераспределении типов лидов.
*   **Неэффективные кампании или источники:** Некоторые кампании или источники показывают низкую конверсию или высокий CPL (стоимость привлечения лида). Это требует анализа и оптимизации маркетинговых стратегий для этих каналов.
*   **Зависимость от определенных кампаний/источников:** Если значительная часть выручки или сделок приходится на ограниченное число кампаний или источников, это может создавать риски при изменении их эффективности или доступности.
*   **Неравномерное распределение нагрузки или эффективности:** Анализ вклада кампаний в выручку по владельцам сделок может выявить, что некоторые менеджеры работают с менее прибыльными кампаниями или не могут эффективно конвертировать лиды из определенных источников.
*   **Потенциальные проблемы с обработкой лидов на определенных стадиях:** Воронка продаж может выявить стадии, на которых происходит наибольшее отсечение лидов, что требует оптимизации процессов на этих этапах.

**Рекомендации:**

*   **Изучить успешные практики:** Проанализировать работу наиболее эффективных владельцев сделок и успешных кампаний/источников для масштабирования их подходов.
*   **Обучение и поддержка:** Предоставить дополнительное обучение менеджерам с низкими показателями конверсии, сфокусировавшись на работе со слабыми стадиями воронки или определенными типами лидов/кампаний.
*   **Оптимизация маркетинговых расходов:** Перераспределить бюджет в пользу наиболее эффективных кампаний и источников, а также проанализировать и улучшить наименее эффективные.
*   **Оптимизация воронки продаж:** Детально изучить стадии с наибольшим отсечением лидов и внести изменения в процессы работы с клиентами на этих этапах.
*   **Анализ связки "менеджер-кампания":** Продолжить анализ эффективности работы менеджеров с конкретными кампаниями для более точного распределения лидов и выявления специфических проблем или успехов.

Этот анализ предоставляет основу для принятия обоснованных решений, направленных на повышение общей эффективности работы отдела продаж и оптимизацию маркетинговых инвестиций.

# **Анализ платежей и продуктов:**

**Анализ типов оплаты и их влияние на успешность сделок**

In [ ]:
payment_success = (
    deals.groupby(['payment_type', 'stage'])
    .size()
    .unstack(fill_value=0)
    .reset_index()
)
payment_success

stage        payment_type  Call Delayed  Free Education  Lost  \
0             One Payment             2               0    15   
1      Recurring Payments             9               0    79   
2             Reservation             0               0     4   
3                 Unknown           372               1  1834   

stage  Need a consultation  New Lead  Payment Done  Qualificated  \
0                        0         0           110             3   
1                        0         0           248             2   
2                        0         0             1             0   
3                        1         1           476            21   

stage  Registered on Offline Day  Registered on Webinar  Waiting For Payment  
0                              0                      0                    2  
1                              0                      1                    1  
2                              0                      0                    0  
3                              1                      2                  319

In [ ]:
print(deals.columns)

Index(['id', 'deal_owner_name', 'closing_date', 'quality', 'stage',
       'lost_reason', 'page', 'campaign', 'content', 'term', 'source',
       'payment_type', 'product', 'education_type', 'created_time',
       'course_duration', 'months_of_study', 'initial_amount_paid',
       'offer_total_amount', 'contact_name', 'city',
       'level_of_deutsch_standardized', 'sla_seconds', 'longitude', 'latitude',
       'country', 'federal_state', 'created_month', 'week', 'closing_month',
       'duration_days', 'closing_week'],
      dtype='object')


In [ ]:
payment_type_counts = deals['payment_type'].value_counts().reset_index()
payment_type_counts.columns = ['payment_type', 'count']

# Создание донат-диаграммы (donut chart)
fig = px.pie(
    payment_type_counts,
    values='count',
    names='payment_type',
    title='Распределение типов оплаты',
    color_discrete_sequence=px.colors.sequential.Blues_r,
    hole=0.4
)

fig.update_traces(
    textinfo='percent+label',  # отображаем долю и метку
    textfont_size=14,
    hovertemplate="<b>%{label}</b><br>Количество: %{value}<br>Доля: %{percent}<extra></extra>"
)

fig.update_layout(
    title=dict(
        text='Распределение типов оплаты',
        x=0.5,
        xanchor='center',
        yanchor='top',
        font=dict(size=22, color='#003366', family='Arial Black'),
        pad=dict(t=80)
    ),
    showlegend=True,
    legend_title_text='Тип оплаты',
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=-0.15,
        xanchor="center",
        x=0.5
    ),
    template='plotly_white',
    margin=dict(t=120, b=60, l=40, r=40)
)

fig.show()

In [ ]:
#percentage of successful transactions for each payment type
payment_total = deals.groupby('payment_type').size()
payment_success_rate = (
    deals[deals['stage'] == 'Payment Done']
    .groupby('payment_type')
    .size() / payment_total
).fillna(0)

# Combine payment type counts and success rates into a single DataFrame
payment_summary = pd.DataFrame({
    'Total Deals': payment_type_counts.set_index('payment_type')['count'],
    'Success Rate (%)': payment_success_rate * 100
}).reset_index()

payment_summary.rename(columns={'index': 'Payment Type'}, inplace=True)

display(payment_summary)

payment_type  Total Deals  Success Rate (%)
0         One Payment          132         83.333333
1  Recurring Payments          340         72.941176
2         Reservation            5         20.000000
3             Unknown         3028         15.719947

Круговая диаграмма показывает, что подавляющее большинство сделок имеют тип оплаты 'Unknown'. Доля других типов оплаты, таких как 'Recurring Payments', 'One Payment' и 'Reservation', значительно меньше. Это указывает на то, что для большей части данных информация о типе оплаты отсутствует или не была зафиксирована.

In [ ]:
#percentage of successful transactions for each payment type
payment_total = deals.groupby('payment_type').size()
payment_success_rate = (
    deals[deals['stage'] == 'Payment Done']
    .groupby('payment_type')
    .size() / payment_total
).fillna(0)

display(payment_total)
display(payment_success)

payment_type
One Payment            132
Recurring Payments     340
Reservation              5
Unknown               3028
dtype: int64

stage        payment_type  Call Delayed  Free Education  Lost  \
0             One Payment             2               0    15   
1      Recurring Payments             9               0    79   
2             Reservation             0               0     4   
3                 Unknown           372               1  1834   

stage  Need a consultation  New Lead  Payment Done  Qualificated  \
0                        0         0           110             3   
1                        0         0           248             2   
2                        0         0             1             0   
3                        1         1           476            21   

stage  Registered on Offline Day  Registered on Webinar  Waiting For Payment  
0                              0                      0                    2  
1                              0                      1                    1  
2                              0                      0                    0  
3                              1                      2                  319

In [ ]:
filtered_payment_success = payment_success[
    payment_success['payment_type'] != 'Unknown'
]

fig = make_subplots(
    rows=1,
    cols=2,
    subplot_titles=(
        "Коэффициент успешности<br>по типам оплаты",
        "Распределение стадий сделок<br>по типам оплаты (без Unknown)",
    ),
    horizontal_spacing=0.15,
)

bar_success_rate = go.Bar(
    x=payment_success_rate.index,
    y=payment_success_rate.values,
    marker=dict(color=px.colors.sequential.Blues_r[3]),
    name='Коэффициент успешности',
)

stages = filtered_payment_success.columns[1:].tolist()
blues_palette = px.colors.sequential.Blues_r

stage_color_map = {}
for i, stage in enumerate(stages):
    if stage == 'Payment Done':
        stage_color_map[stage] = blues_palette[-1]
    else:
        stage_color_map[stage] = blues_palette[i % len(blues_palette)]


for stage in stages:
    fig.add_trace(
        go.Bar(
            x=filtered_payment_success['payment_type'],
            y=filtered_payment_success[stage],
            name=stage,
            marker_color=stage_color_map[stage],
        ),
        row=1,
        col=2,
    )


fig.add_trace(bar_success_rate, row=1, col=1)


fig.update_layout(
    title=dict(
        text="Анализ типов оплаты и успешности сделок",
        x=0.5,
        xanchor='center',
        yanchor='top',
        font=dict(size=22, color='#003366', family='Arial Black'),
        pad=dict(t=80),  # увеличен отступ заголовка от графиков
    ),
    showlegend=True,
    legend_title_text='Стадия сделки',
    template='plotly_white',
    height=550,
    width=1200,
    barmode='stack',
    bargap=0.1,
    bargroupgap=0.1,
    margin=dict(t=150, b=60, l=60, r=40),
)


fig.update_xaxes(title_text="Тип оплаты", row=1, col=1)
fig.update_yaxes(title_text="Доля успешных сделок", row=1, col=1)
fig.update_xaxes(title_text="Тип оплаты", row=1, col=2)
fig.update_yaxes(title_text="Количество сделок", row=1, col=2)

fig.show()

Типы оплаты 'One Payment' и 'Recurring Payments' имеют значительное количество сделок на стадии 'Payment Done', что указывает на их успешность. Тип оплаты 'Reservation' имеет очень мало сделок в целом, и только одну на стадии 'Payment Done'. Это говорит о том, что 'Reservation' пока не так популярен или успешен по сравнению с другими типами оплаты.

Таким образом, большой процент "Unknown" на круговой диаграмме говорит о проблеме с данными, а низкий процент успешности в этой категории указывает на то, что сделки с неизвестным типом оплаты редко завершаются успешно. График распределения стадий для известных типов оплаты показывает, что "Recurring Payments" и "One Payment" являются основными источниками успешных сделок по количеству, при этом "One Payment" демонстрирует более высокую долю успешных сделок относительно их общего числа.

**2. Анализ продуктов и типов обучения**

In [ ]:
display(deals['product'].value_counts())
display(deals['education_type'].value_counts())

product
Digital Marketing    1942
UX/UI Design          999
Web Developer         564
Name: count, dtype: int64

education_type
Morning    2822
Evening     398
Unknown     285
Name: count, dtype: int64

In [ ]:
product_counts = deals['product'].value_counts().reset_index()
product_counts.columns = ['product', 'count']

education_type_counts = deals['education_type'].value_counts().reset_index()
education_type_counts.columns = ['education_type', 'count']

fig = make_subplots(
    rows=1,
    cols=2,
    specs=[[{'type': 'domain'}, {'type': 'domain'}]],
    subplot_titles=('Распределение продуктов', 'Распределение типов обучения'),
    horizontal_spacing=0.1  # расстояние между диаграммами
)

# 1. Пончик: распределение продуктов
fig.add_trace(
    go.Pie(
        labels=product_counts['product'],
        values=product_counts['count'],
        name='Products',
        marker=dict(colors=px.colors.sequential.Blues_r),
        textinfo='percent+label',
        hole=0.4
    ),
    row=1, col=1
)

# 2. Пончик: распределение типов обучения
fig.add_trace(
    go.Pie(
        labels=education_type_counts['education_type'],
        values=education_type_counts['count'],
        name='Education Types',
        marker=dict(colors=px.colors.sequential.Blues_r),
        textinfo='percent+label',
        hole=0.4
    ),
    row=1, col=2
)

fig.update_layout(
    title_text='Распределение продуктов и типов обучения',
    height=600,
    width=1200,
    showlegend=True,
    legend=dict(
        orientation='v',
        yanchor='top',
        y=1,
        xanchor='right',
        x=1.15,  # легенда справа от обоих графиков
        font=dict(size=12)
    ),
    title_font=dict(size=22, color="#003366", family="Arial Black"),
)

fig.show()

In [ ]:
product_total = deals.groupby('product').size()

product_success_rate = (
    deals[deals['stage'] == 'Payment Done']
    .groupby('product')
    .size()
    / product_total
).fillna(0).sort_values(ascending=False)

education_type_total = deals.groupby('education_type').size()

education_type_success_rate = (
    deals[deals['stage'] == 'Payment Done']
    .groupby('education_type')
    .size()
    / education_type_total
).fillna(0).sort_values(ascending=False)

print("Процент успешности по продуктам:")
display(product_success_rate)
print("Процент успешности по типам обучения:")
display(education_type_success_rate)

Процент успешности по продуктам:


product
Digital Marketing    0.243048
Web Developer        0.241135
UX/UI Design         0.227227
dtype: float64

Процент успешности по типам обучения:


education_type
Evening    0.427136
Morning    0.233168
Unknown    0.024561
dtype: float64

In [ ]:
filtered_product_success_rate = product_success_rate[
    product_success_rate.index != 'Unknown'
]
filtered_education_type_success_rate = education_type_success_rate[
    education_type_success_rate.index != 'Unknown'
]

fig = make_subplots(
    rows=1,
    cols=2,
    specs=[[{'type': 'domain'}, {'type': 'domain'}]],
    subplot_titles=(
        'Процент успешности по продуктам (без Unknown)',
        'Процент успешности по типам обучения (без Unknown)',
    ),
    horizontal_spacing=0.1,
)

# 1.Пончик: успешность по продуктам
fig.add_trace(
    go.Pie(
        labels=filtered_product_success_rate.index,
        values=filtered_product_success_rate.values,
        name='Product Success Rate',
        marker=dict(colors=px.colors.sequential.Blues_r),
        textinfo='percent+label',
        hole=0.4,
    ),
    row=1,
    col=1,
)

# 2.Пончик: успешность по типам обучения
fig.add_trace(
    go.Pie(
        labels=filtered_education_type_success_rate.index,
        values=filtered_education_type_success_rate.values,
        name='Education Success Rate',
        marker=dict(colors=px.colors.sequential.Blues_r),
        textinfo='percent+label',
        hole=0.4,
    ),
    row=1,
    col=2,
)

fig.update_layout(
    title_text='Процент успешности по продуктам и типам обучения (без Unknown)',
    height=600,
    width=1200,
    showlegend=True,
    legend=dict(
        orientation='v',
        yanchor='top',
        y=1,
        xanchor='right',
        x=1.1,
        font=dict(size=12),
    ),
    title_font=dict(size=22, color='#003366', family='Arial Black'),
)

fig.show()

**Продукты:** Среди продуктов с известным типом, 'Digital Marketing' и 'Web Developer' имеют самые высокие показатели успешности, очень близкие друг к другу (около 24%). 'UX/UI Design' немного ниже. Продукт 'Unknown' имеет минимальный процент успешности. Это говорит о том, что при наличии данных о продукте, сделки по 'Digital Marketing' и 'Web Developer' наиболее вероятно завершаются успешно.

**Типы обучения:** Тип обучения 'Evening' выделяется значительно более высоким процентом успешности (около 42.7%) по сравнению с типом 'Morning' (около 23.3%). Как и в случае с продуктами, тип обучения 'Unknown' имеет крайне низкий процент успешности. Это указывает на то, что вечерний формат обучения ассоциируется с более высокой конверсией в оплату.

**Общие выводы по анализу платежей, продуктов и типов обучения:**

***Проблема с данными "Unknown":*** Значительная доля сделок имеет неизвестные тип оплаты, продукт и тип обучения. Эти сделки демонстрируют крайне низкий процент успешности. Это указывает на серьезную проблему с сбором или фиксацией данных, которая мешает полноценному анализу и может скрывать важные закономерности. Решение этой проблемы должно быть приоритетом для улучшения качества данных и аналитики.

***Успешность по типам оплаты (среди известных):*** Типы оплаты 'One Payment' и 'Recurring Payments' являются основными успешными типами. При этом 'One Payment' имеет более высокий процент успешности, а 'Recurring Payments' - большее абсолютное количество успешных сделок. Тип 'Reservation' пока не является значимым по объему или успешности.

***Успешность по продуктам (среди известных):*** Продукты 'Digital Marketing' и 'Web Developer' показывают самые высокие и схожие проценты успешности среди известных продуктов. 'UX/UI Design' немного уступает им.

***Успешность по типам обучения (среди известных):*** Тип обучения 'Evening' значительно выделяется своим высоким процентом успешности по сравнению с типом 'Morning'. Это может быть важным фактором для оптимизации маркетинговых усилий или предложения продуктов.


**Рекомендации:**



*   Необходимо улучшить процессы сбора данных для минимизации категории "Unknown".
*   Стоит более детально изучить факторы, способствующие высокой успешности сделок с типом оплаты 'One Payment' и типом обучения 'Evening'.
*   Анализ данных без категории "Unknown" дает более реалистичное представление об успешности различных категорий.



# **Географический анализ сделок по городам**

**Анализ географического распределения сделок по городам**

In [ ]:
print("Deals DataFrame columns:", deals.columns.tolist())

Deals DataFrame columns: ['id', 'deal_owner_name', 'closing_date', 'quality', 'stage', 'lost_reason', 'page', 'campaign', 'content', 'term', 'source', 'payment_type', 'product', 'education_type', 'created_time', 'course_duration', 'months_of_study', 'initial_amount_paid', 'offer_total_amount', 'contact_name', 'city', 'level_of_deutsch_standardized', 'sla_seconds', 'longitude', 'latitude', 'country', 'federal_state', 'created_month', 'week', 'closing_month', 'duration_days', 'closing_week']


In [ ]:
deals['city'] = deals.city.replace('-', "Unnamed")

In [ ]:
geo_deals_df = deals[['id', 'city']]
geo_deals_df_clean = geo_deals_df.dropna(subset=['city'])
deals_by_city = geo_deals_df_clean.groupby('city').size().reset_index(name='Number of Deals')

deals_by_city_sorted = deals_by_city.sort_values(by='Number of Deals', ascending=False)
deals_by_city_sorted

city  Number of Deals
772     Unknown             1411
85       Berlin              174
519     München               71
286     Hamburg               60
428     Leipzig               45
..          ...              ...
11    Aidlingen                1
12        Ajman                1
13     Alamudun                1
15   Aldenhoven                1
17    Allendorf                1

[866 rows x 2 columns]

In [ ]:
# geo_data_deals = deals[["city", "longitude", "latitude", "country_ru",
#                            "city_ru"]].drop_duplicates(subset=["city"]).dropna()
geo_data_deals = deals[["city", "longitude", "latitude"]].drop_duplicates(subset=["city"]).dropna()

In [ ]:
deals_by_city_sorted = deals_by_city_sorted.merge(geo_data_deals, on='city', how="inner")
deals_by_city_sorted

city  Number of Deals  longitude   latitude
0        Berlin              174  13.404954  52.520007
1       München               71  11.581981  48.135125
2       Hamburg               60   9.987170  53.548828
3       Leipzig               45  12.373075  51.339695
4      Nürnberg               42  11.074564  49.454288
..          ...              ...        ...        ...
860   Aidlingen                1   8.895746  48.679056
861       Ajman                1  55.513643  25.405217
862    Alamudun                1  74.634187  42.907267
863  Aldenhoven                1   6.287122  50.894882
864   Allendorf                1   8.670368  51.026463

[865 rows x 4 columns]

In [ ]:
columns_needed = ["city", "stage", "level_of_deutsch_standardized", "product"]

deals_analysis_df = deals.copy()

# Filter only required columns
deals_analysis_df = deals_analysis_df[
    [col for col in columns_needed if col in deals_analysis_df.columns]
].copy()

# Drop rows where city is missing
deals_analysis_df = deals_analysis_df.dropna(subset=["city"])

# Mark successful deals
deals_analysis_df["is_success"] = deals_analysis_df["stage"].apply(
    lambda x: 1 if str(x).strip().lower() == "payment done" else 0
)

# === Geographical distribution of transactions ===
city_summary = (
    deals_analysis_df
    .groupby("city", as_index=False)
    .agg(
        total_deals=("stage", "count"),
        successful=("is_success", "sum")
    )
)

city_summary["success_rate"] = (
    city_summary["successful"] / city_summary["total_deals"] * 100
).round(2)

print("Таблица распределения сделок по городам:")
print(city_summary.sort_values("total_deals", ascending=False).head())

Таблица распределения сделок по городам:
        city  total_deals  successful  success_rate
772  Unknown         1411         116          8.22
85    Berlin          174          78         44.83
519  München           71          27         38.03
286  Hamburg           60          22         36.67
428  Leipzig           45          18         40.00


In [ ]:
city_summary_filtered = city_summary[
    ~city_summary["city"].isin(["Unknown", "-"])
].copy()

fig2 = px.bar(
    city_summary_filtered.sort_values("total_deals", ascending=False).head(20),  # Top 20 cities
    x="city",
    y="total_deals",
    color="total_deals",
    text="total_deals",
    color_continuous_scale=px.colors.sequential.Blues,
    title="Распределение сделок по городам (исключая 'Unknown' и '-')"
)

fig2.update_layout(template="plotly_white", xaxis_tickangle=45)
fig2.show()

In [ ]:
# Filter cities with more than a certain number of deals (e.g., > 5 deals)
deals_by_city_filtered = deals_by_city_sorted[deals_by_city_sorted['Number of Deals'] > 5].copy()

fig = px.scatter_geo(
    deals_by_city_filtered,
    lat="latitude",
    lon="longitude",
    size="Number of Deals",
    hover_name="city",
    projection="natural earth",
    title="Географическое распределение сделок по городам (более 5 сделок)",
    color="Number of Deals",
    color_continuous_scale=px.colors.sequential.Blues,
    size_max=30 # Increase size for better visibility
)

fig.update_layout(
    geo=dict(
        showland=True,
        landcolor="lightgray",
        showocean=True,
        oceancolor="lightblue",
        scope='europe'
    ),
    height=700,
    width=1000,
    margin=dict(l=0, r=0, t=50, b=0)
)

fig.show()

**Анализ влияния уровня знания немецкого языка на успешность сделок по городам.**

In [ ]:
lang_success = (
    deals_analysis_df
    .groupby(["city", "level_of_deutsch_standardized"], as_index=False)
    .agg(
        total_deals=("stage", "count"),
        successful=("is_success", "sum")
    )
)

lang_success["success_rate"] = (
    lang_success["successful"] / lang_success["total_deals"] * 100
).round(2)

print("\nТаблица успешности сделок по городам и уровню немецкого языка:")
print(lang_success.head())


Таблица успешности сделок по городам и уровню немецкого языка:
        city level_of_deutsch_standardized  total_deals  successful  \
0     Aachen                            A2            1           0   
1     Aachen                            B1            5           2   
2     Aachen                       Unknown            3           1   
3      Aalen                       Unknown            1           0   
4  Abensberg                       Unknown            1           0   

   success_rate  
0          0.00  
1         40.00  
2         33.33  
3          0.00  
4          0.00  


In [ ]:
lang_success_filtered = lang_success[
    ~lang_success["city"].isin(["Unknown", "-"]) &
    ~lang_success["level_of_deutsch_standardized"].isin(["Unknown", "-"])
].copy()

print("Переменная 'lang_success_filtered' определена.")

fig = make_subplots(
    rows=1,
    cols=1,
    subplot_titles=(
        "Влияние уровня немецкого языка<br> на успешность сделок по городам (Тепловая карта) ",
    ),
)

heatmap = go.Heatmap(
    x=lang_success_filtered["level_of_deutsch_standardized"],
    y=lang_success_filtered["city"],
    z=lang_success_filtered["success_rate"],
    colorscale=px.colors.sequential.Blues,
    colorbar=dict(title="Конверсия (%)"),
)
fig.add_trace(heatmap, row=1, col=1)


fig.update_layout(
    template="plotly_white",
    height=800,
    showlegend=False
)

fig.update_xaxes(title_text="Уровень немецкого языка", row=1, col=1)
fig.update_yaxes(title_text="Город", row=1, col=1)

fig.show()

Переменная 'lang_success_filtered' определена.


In [ ]:
product_city_success = (
    deals_analysis_df
    .groupby(["city", "product"], as_index=False)
    .agg(
        total_deals=("stage", "count"),
        successful=("is_success", "sum"),
    )
)

product_city_success["success_rate"] = (
    product_city_success["successful"] / product_city_success["total_deals"] * 100
).round(2)

print("\nТаблица успешности сделок по продуктам и городам:")
print(product_city_success.head(10))

In [ ]:
product_city_success_filtered = product_city_success[
    product_city_success["city"] != "-"
].copy()

fig6 = px.density_heatmap(
    product_city_success_filtered,
    x="product",
    y="city",
    z="success_rate",
    color_continuous_scale=px.colors.sequential.Blues,
    title="Тепловая карта успешности сделок по продуктам и городам (без города '-')",
    labels={"success_rate": "Конверсия (%)", "product": "Продукт", "city": "Город"},
)

fig6.update_layout(
    template="plotly_white",
    height=900,  # Increase height for better readability of cities
)

fig6.show()

In [ ]:
total_deals_count = city_summary["total_deals"].sum()

unknown_deals_count = city_summary[
    city_summary["city"].isin(["Unknown", "-"])
]["total_deals"].sum()

percentage_unknown = (unknown_deals_count / total_deals_count * 100).round(2)

print(
    f"Процент сделок с отсутствующим или неизвестным городом ('Unknown' или '-'): {percentage_unknown}%"
)

In [ ]:
# Calculate total sales amount by city
city_sales = deals.groupby('city')['offer_total_amount'].sum().reset_index(name='Total Sales Amount')

# Sort by total sales amount and display top cities
display(city_sales.sort_values(by='Total Sales Amount', ascending=False).head(10))

### Анализ географического распределения сделок по городам

На основе анализа данных по городам можно сделать следующие выводы:

*   Значительная часть данных о городах для сделок отсутствует или указана как "Unknown" или "-". Эти категории составляют наибольшее количество сделок.
*   Среди городов, для которых есть данные, наибольшее количество сделок наблюдается в **Берлине**, за которым следуют **Мюнхен** и **Гамбург**.
*   Распределение сделок по другим городам значительно ниже по объему.



На основе проведенного анализа можно сделать следующие выводы:

**Влияние уровня знания немецкого языка на успешность сделок:**

*   В целом, наблюдается положительная тенденция: более высокие уровни владения немецким языком (особенно B1 и выше) коррелируют с более высокой конверсией сделок в большинстве городов.
*   Однако, эта зависимость не является абсолютной и может варьироваться в зависимости от конкретного города, что указывает на влияние других локальных факторов.
*   Для многих комбинаций городов и уровней языка данных недостаточно для однозначных выводов.

**Успешность сделок по продуктам и городам:**

*   Успешность сделок значительно различается в зависимости от комбинации продукта и города. Некоторые продукты показывают высокую конверсию в одних городах и низкую в других.
*   Тепловая карта позволяет наглядно увидеть эти различия и выявить наиболее успешные комбинации "продукт-город".
*   Анализ успешности по продуктам в разрезе городов помогает выявить региональные особенности спроса и эффективности продаж для различных предложений.

**Общие рекомендации:**

*   Для улучшения общей конверсии важно учитывать как географическое распределение клиентов, так и их уровень владения языком, а также специфику спроса на различные продукты в конкретных регионах.
*   Целесообразно сосредоточить усилия на городах и комбинациях "продукт-уровень языка", где наблюдается наибольший потенциал для успешных сделок.
*   Необходимо уделить внимание сбору более полных данных о городах для сделок, так как значительная часть информации отсутствует.

# **`Общий вывод по анализу данных`**

На основе проведенного всестороннего анализа данных о звонках, сделках, маркетинговых кампаниях, платежах, продуктах, типах обучения и географическом распределении можно сделать следующие ключевые выводы:

1.  **Взаимосвязь маркетинга и продаж:** Существует сильная положительная корреляция между активностью звонков и созданием новых сделок, что подчеркивает важность эффективного взаимодействия отдела продаж с потенциальными клиентами, привлеченными маркетингом.
2.  **Эффективность кампаний и источников:** Выявлены как высокообъемные кампании, привлекающие большое количество лидов, так и высококонверсионные кампании, приносящие "качественные" сделки. Однако, значительная часть кампаний имеет нулевую конверсию, что требует детального изучения и оптимизации.
3.  **Эффективность отдела продаж:** Определены менеджеры с высокой конверсией и значительным вкладом в выручку. Анализ длительности сделок по стадиям выявил потенциальные узкие места в процессе продаж, где сделки могут задерживаться.
4.  **Влияние типов оплаты, продуктов и обучения:** Типы оплаты "One Payment" и "Recurring Payments", а также продукты "Digital Marketing" и "Web Developer" и тип обучения "Evening" показывают более высокий процент успешности сделок по сравнению с другими категориями.
5.  **Географическое распределение и качество данных:** Географический анализ выявил концентрацию сделок в крупных городах, но значительная часть данных о городах, продуктах и типах оплаты отсутствует или некорректна ("Unknown", "-"), что существенно ограничивает глубину анализа и скрывает потенциальные закономерности.

**Рекомендации для улучшения:**

*   **Улучшение качества данных:** Приоритетной задачей является повышение точности и полноты данных, особенно по типам оплаты, продуктам, типам обучения и городам, чтобы минимизировать категорию "Unknown" и обеспечить более глубокий анализ.
*   **Оптимизация неэффективных кампаний:** Провести детальный анализ кампаний с нулевой или низкой конверсией для выявления причин и внесения корректировок в таргетинг, креативы, сообщения или посадочные страницы.
*   **Обучение и развитие отдела продаж:** Предоставить целевое обучение менеджерам с низкими показателями конверсии, сфокусировавшись на работе с конкретными стадиями воронки или типами лидов/кампаний, где наблюдаются трудности.
*   **Оптимизация процессов продаж:** Изучить и улучшить этапы воронки продаж, на которых наблюдается наибольшее отсечение лидов или аномально долгая длительность сделок.
*   **Фокус на успешных сегментах:** Масштабировать усилия на маркетинговые каналы, продукты, типы обучения и географические регионы с доказанной высокой эффективностью (высокая конверсия, низкий CPW) для максимизации прибыли.